/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DBTools.DB_ConnectionManager;
//import managerdatenpflegewerkzeugstamm.CustomTableCellRenderer;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import javax.swing.BoundedRangeModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author schmidtu
 */
public class Frame_DataMaintenance_Grundformstamm extends javax.swing.JFrame {
    static int InstanceCount;

    /**
     * Creates new form Frame_DataMaintenance_Grundformstamm
     */
    public Frame_DataMaintenance_Grundformstamm() {
        InstanceCount++;
        this.Old_Bezeichnung = "";
        this.Old_Beschreibung = "";
        this.Old_Druckrahmen = "";
        this.Old_Segmentrahmen = "";
        this.Old_Unterbauleiste = "";
        this.Old_Kühlplatte = "";
        this.Old_Grundplatte = "";
        this.Old_Druckplatte = "";
        this.DataSet_Mode = "clean";
        initComponents();
        btn_edit.setEnabled(false);
        btn_duplicate.setEnabled(false);
        btn_delete.setEnabled(false);
        btn_accept.setEnabled(false);
        btn_cancel.setEnabled(false);
    } 
    public int getInstance() {
        return InstanceCount;
    }   
   
    boolean myAnswerIfConnected;
    Connection myConnection;
    DefaultTableModel myTableModel; 
    TableRowSorter<DefaultTableModel> mySorter;          
    DB_ConnectionManager MY_DBCM;
    String Old_Key;
    String Old_Bezeichnung;
    String Old_Beschreibung;
    String Old_Druckrahmen;
    String Old_Segmentrahmen;
    String Old_Unterbauleiste;
    String Old_Kühlplatte;
    String Old_Grundplatte;
    String Old_Druckplatte;
    String Old_Anlagedatum;
    String Old_Änderungsdatum;
    String Old_Benutzer;
    int OldSelection;
    String DataSet_Mode;
    Timestamp Anlagedatum;
    Timestamp Änderungsdatum;
    String Benutzer;
    String MyDependentValue_Bezeichnung;
    int TableColumns;
    
    private void do_preBuild() {        
        getDBConnection();
        get_DBTableData();
        myTableModel = (DefaultTableModel) jTable_dbData.getModel();
        createRowSorter(myTableModel);
        lbl_rowCount.setText(String.valueOf(mySorter.getViewRowCount()) + " von " + String.valueOf(myTableModel.getRowCount()));
        
        final BoundedRangeModel scrollModel = jScrollPane_dbData.getHorizontalScrollBar().getModel();
        jScrollPane_editData.getHorizontalScrollBar().setModel(scrollModel);
    }
    
    private void createRowSorter(DefaultTableModel aModel) {
        mySorter = new TableRowSorter<>(aModel);
        jTable_dbData.setRowSorter(mySorter);
    }
    
    private void search() {
        String searchTerm = jTextField_searchValue.getText();
        mySorter.setRowFilter(RowFilter.regexFilter(searchTerm));
    }
    
    private void do_postBuild() {                
        jTable_dbData.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {
            set_valuesIntoTextFields();
        });
        KeyListener tfKeyListener = new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent evt) {
                if (evt.getKeyCode() == KeyEvent.VK_ENTER)
                    btn_accept.doClick();
                if (evt.getKeyCode() == KeyEvent.VK_DELETE)
                    btn_delete.doClick();
            }
        };
        jTextField_key.addKeyListener(tfKeyListener);
        jFormattedTextField_Bezeichnung.addKeyListener(tfKeyListener);
        jFormattedTextField_Druckrahmen.addKeyListener(tfKeyListener);
        jFormattedTextField_Segmentrahmen.addKeyListener(tfKeyListener);
        jFormattedTextField_Unterbauleiste.addKeyListener(tfKeyListener);
        jFormattedTextField_Kühlplatte.addKeyListener(tfKeyListener);
        jFormattedTextField_Grundplatte.addKeyListener(tfKeyListener);
        jFormattedTextField_Druckplatte.addKeyListener(tfKeyListener);
        jTable_dbData.addKeyListener(tfKeyListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_base = new javax.swing.JPanel();
        jPanel_table = new javax.swing.JPanel();
        jTextField_searchValue = new javax.swing.JTextField();
        btn_deleteSearchValue = new javax.swing.JButton();
        jScrollPane_dbData = new javax.swing.JScrollPane();
        jTable_dbData = new javax.swing.JTable();
        lbl_search1 = new javax.swing.JLabel();
        lbl_rowCount = new javax.swing.JLabel();
        btn_getCurrentDBData = new javax.swing.JButton();
        lbl_tableName = new javax.swing.JLabel();
        jPanel_footer = new javax.swing.JPanel();
        btn_close = new javax.swing.JButton();
        jScrollPane_editData = new javax.swing.JScrollPane();
        jPanel_editData = new javax.swing.JPanel();
        jPanel_editLabels = new javax.swing.JPanel();
        lbl_key = new javax.swing.JLabel();
        lbl_Bezeichnung = new javax.swing.JLabel();
        lbl_Beschreibung = new javax.swing.JLabel();
        lbl_Druckrahmen = new javax.swing.JLabel();
        btn_openDialog_Druckrahmen = new javax.swing.JButton();
        btn_delete_Druckrahmen = new javax.swing.JButton();
        jLabel_Segmentrahmen = new javax.swing.JLabel();
        btn_openDialog_Segmentrahmen = new javax.swing.JButton();
        btn_delete_Segmentrahmen = new javax.swing.JButton();
        jLabel_Unterbauleiste = new javax.swing.JLabel();
        btn_openDialog_Unterbauleiste = new javax.swing.JButton();
        btn_delete_Unterbauleiste = new javax.swing.JButton();
        jLabel_Kühlplatte = new javax.swing.JLabel();
        btn_openDialog_Kühlplatte = new javax.swing.JButton();
        btn_delete_Kühlplatte = new javax.swing.JButton();
        jLabel_Grundplatte = new javax.swing.JLabel();
        btn_openDialog_Grundplatte = new javax.swing.JButton();
        btn_delete_Grundplatte = new javax.swing.JButton();
        jLabel_Druckplatte = new javax.swing.JLabel();
        btn_openDialog_Druckplatte = new javax.swing.JButton();
        btn_delete_Druckplatte = new javax.swing.JButton();
        jPanel_editTextFields = new javax.swing.JPanel();
        jTextField_key = new javax.swing.JTextField();
        jFormattedTextField_Bezeichnung = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Beschreibung = new javax.swing.JTextArea();
        jFormattedTextField_Druckrahmen = new javax.swing.JFormattedTextField();
        jFormattedTextField_Segmentrahmen = new javax.swing.JTextField();
        jFormattedTextField_Unterbauleiste = new javax.swing.JTextField();
        jFormattedTextField_Kühlplatte = new javax.swing.JTextField();
        jFormattedTextField_Grundplatte = new javax.swing.JTextField();
        jFormattedTextField_Druckplatte = new javax.swing.JTextField();
        btn_new = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_accept = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        btn_duplicate = new javax.swing.JButton();
        lbl_Anlagedatum = new javax.swing.JLabel();
        lbl_Änderungsdatum = new javax.swing.JLabel();
        lbl_Benutzer = new javax.swing.JLabel();
        jTextField_Anlagedatum = new javax.swing.JTextField();
        jTextField_Änderungsdatum = new javax.swing.JTextField();
        jTextField_Benutzer = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel_base.setBackground(new java.awt.Color(204, 255, 255));

        jPanel_table.setOpaque(false);

        jTextField_searchValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_searchValueKeyReleased(evt);
            }
        });

        btn_deleteSearchValue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Löschen.png"))); // NOI18N
        btn_deleteSearchValue.setPreferredSize(new java.awt.Dimension(23, 23));
        btn_deleteSearchValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteSearchValueActionPerformed(evt);
            }
        });

        jTable_dbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "GF (Key)", "Bezeichnung", "Beschreibung", "Druckrahmen", "Segmentrahmen", "Unterbauleiste", "Kühlplatte", "Grundplatte", "Druckplatte", "Anlagedatum", "Änderungsdatum", "Benutzer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_dbData.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable_dbData.setRowHeight(20);
        jTable_dbData.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable_dbData.getTableHeader().setReorderingAllowed(false);
        jScrollPane_dbData.setViewportView(jTable_dbData);
        if (jTable_dbData.getColumnModel().getColumnCount() > 0) {
            jTable_dbData.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable_dbData.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTable_dbData.getColumnModel().getColumn(2).setPreferredWidth(200);
            jTable_dbData.getColumnModel().getColumn(3).setPreferredWidth(150);
            jTable_dbData.getColumnModel().getColumn(4).setPreferredWidth(150);
            jTable_dbData.getColumnModel().getColumn(5).setPreferredWidth(150);
            jTable_dbData.getColumnModel().getColumn(6).setPreferredWidth(150);
            jTable_dbData.getColumnModel().getColumn(7).setPreferredWidth(150);
            jTable_dbData.getColumnModel().getColumn(8).setPreferredWidth(150);
            jTable_dbData.getColumnModel().getColumn(9).setPreferredWidth(150);
            jTable_dbData.getColumnModel().getColumn(10).setPreferredWidth(150);
            jTable_dbData.getColumnModel().getColumn(11).setPreferredWidth(150);
        }

        lbl_search1.setText("Suchen");

        lbl_rowCount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        btn_getCurrentDBData.setText("Aktualisieren");
        btn_getCurrentDBData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_getCurrentDBDataActionPerformed(evt);
            }
        });

        lbl_tableName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_tableName.setText("Tabelle: Grundformstamm");

        javax.swing.GroupLayout jPanel_tableLayout = new javax.swing.GroupLayout(jPanel_table);
        jPanel_table.setLayout(jPanel_tableLayout);
        jPanel_tableLayout.setHorizontalGroup(
            jPanel_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_tableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_dbData)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_tableLayout.createSequentialGroup()
                        .addGroup(jPanel_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_tableLayout.createSequentialGroup()
                                .addComponent(jTextField_searchValue, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_deleteSearchValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_getCurrentDBData))
                            .addComponent(lbl_tableName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1963, Short.MAX_VALUE)
                        .addComponent(lbl_rowCount, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_tableLayout.createSequentialGroup()
                        .addComponent(lbl_search1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_tableLayout.setVerticalGroup(
            jPanel_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_tableLayout.createSequentialGroup()
                .addGroup(jPanel_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_tableLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbl_tableName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_search1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_searchValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_deleteSearchValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_getCurrentDBData)))
                    .addGroup(jPanel_tableLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lbl_rowCount, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_dbData, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel_footer.setOpaque(false);

        btn_close.setText("Schließen");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_footerLayout = new javax.swing.GroupLayout(jPanel_footer);
        jPanel_footer.setLayout(jPanel_footerLayout);
        jPanel_footerLayout.setHorizontalGroup(
            jPanel_footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_footerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_close)
                .addContainerGap(845, Short.MAX_VALUE))
        );
        jPanel_footerLayout.setVerticalGroup(
            jPanel_footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_footerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_close)
                .addGap(23, 23, 23))
        );

        jScrollPane_editData.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel_editData.setBorder(javax.swing.BorderFactory.createTitledBorder("Bearbeitung"));
        jPanel_editData.setOpaque(false);

        jPanel_editLabels.setOpaque(false);
        jPanel_editLabels.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        lbl_key.setText("GF (Key)");
        lbl_key.setPreferredSize(new java.awt.Dimension(100, 14));
        jPanel_editLabels.add(lbl_key);

        lbl_Bezeichnung.setText("Bezeichnung");
        lbl_Bezeichnung.setPreferredSize(new java.awt.Dimension(200, 14));
        jPanel_editLabels.add(lbl_Bezeichnung);

        lbl_Beschreibung.setText("Beschreibung");
        lbl_Beschreibung.setPreferredSize(new java.awt.Dimension(200, 14));
        jPanel_editLabels.add(lbl_Beschreibung);

        lbl_Druckrahmen.setText("Druckrahmen");
        lbl_Druckrahmen.setPreferredSize(new java.awt.Dimension(104, 14));
        jPanel_editLabels.add(lbl_Druckrahmen);

        btn_openDialog_Druckrahmen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Lupe.png"))); // NOI18N
        btn_openDialog_Druckrahmen.setEnabled(false);
        btn_openDialog_Druckrahmen.setPreferredSize(new java.awt.Dimension(23, 23));
        btn_openDialog_Druckrahmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_openDialog_DruckrahmenActionPerformed(evt);
            }
        });
        jPanel_editLabels.add(btn_openDialog_Druckrahmen);

        btn_delete_Druckrahmen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Löschen.png"))); // NOI18N
        btn_delete_Druckrahmen.setEnabled(false);
        btn_delete_Druckrahmen.setPreferredSize(new java.awt.Dimension(23, 23));
        btn_delete_Druckrahmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_DruckrahmenActionPerformed(evt);
            }
        });
        jPanel_editLabels.add(btn_delete_Druckrahmen);

        jLabel_Segmentrahmen.setText("Segmentrahmen");
        jLabel_Segmentrahmen.setPreferredSize(new java.awt.Dimension(104, 14));
        jPanel_editLabels.add(jLabel_Segmentrahmen);

        btn_openDialog_Segmentrahmen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Lupe.png"))); // NOI18N
        btn_openDialog_Segmentrahmen.setEnabled(false);
        btn_openDialog_Segmentrahmen.setPreferredSize(new java.awt.Dimension(23, 23));
        btn_openDialog_Segmentrahmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_openDialog_SegmentrahmenActionPerformed(evt);
            }
        });
        jPanel_editLabels.add(btn_openDialog_Segmentrahmen);

        btn_delete_Segmentrahmen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Löschen.png"))); // NOI18N
        btn_delete_Segmentrahmen.setEnabled(false);
        btn_delete_Segmentrahmen.setPreferredSize(new java.awt.Dimension(23, 23));
        btn_delete_Segmentrahmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_SegmentrahmenActionPerformed(evt);
            }
        });
        jPanel_editLabels.add(btn_delete_Segmentrahmen);

        jLabel_Unterbauleiste.setText("Unterbauleiste");
        jLabel_Unterbauleiste.setPreferredSize(new java.awt.Dimension(104, 14));
        jPanel_editLabels.add(jLabel_Unterbauleiste);

        btn_openDialog_Unterbauleiste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Lupe.png"))); // NOI18N
        btn_openDialog_Unterbauleiste.setEnabled(false);
        btn_openDialog_Unterbauleiste.setPreferredSize(new java.awt.Dimension(23, 23));
        btn_openDialog_Unterbauleiste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_openDialog_UnterbauleisteActionPerformed(evt);
            }
        });
        jPanel_editLabels.add(btn_openDialog_Unterbauleiste);

        btn_delete_Unterbauleiste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Löschen.png"))); // NOI18N
        btn_delete_Unterbauleiste.setEnabled(false);
        btn_delete_Unterbauleiste.setPreferredSize(new java.awt.Dimension(23, 23));
        btn_delete_Unterbauleiste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_UnterbauleisteActionPerformed(evt);
            }
        });
        jPanel_editLabels.add(btn_delete_Unterbauleiste);

        jLabel_Kühlplatte.setText("Kühlplatte");
        jLabel_Kühlplatte.setPreferredSize(new java.awt.Dimension(104, 14));
        jPanel_editLabels.add(jLabel_Kühlplatte);

        btn_openDialog_Kühlplatte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Lupe.png"))); // NOI18N
        btn_openDialog_Kühlplatte.setEnabled(false);
        btn_openDialog_Kühlplatte.setPreferredSize(new java.awt.Dimension(23, 23));
        btn_openDialog_Kühlplatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_openDialog_KühlplatteActionPerformed(evt);
            }
        });
        jPanel_editLabels.add(btn_openDialog_Kühlplatte);

        btn_delete_Kühlplatte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Löschen.png"))); // NOI18N
        btn_delete_Kühlplatte.setEnabled(false);
        btn_delete_Kühlplatte.setPreferredSize(new java.awt.Dimension(23, 23));
        btn_delete_Kühlplatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_KühlplatteActionPerformed(evt);
            }
        });
        jPanel_editLabels.add(btn_delete_Kühlplatte);

        jLabel_Grundplatte.setText("Grundplatte");
        jLabel_Grundplatte.setPreferredSize(new java.awt.Dimension(104, 14));
        jPanel_editLabels.add(jLabel_Grundplatte);

        btn_openDialog_Grundplatte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Lupe.png"))); // NOI18N
        btn_openDialog_Grundplatte.setEnabled(false);
        btn_openDialog_Grundplatte.setPreferredSize(new java.awt.Dimension(23, 23));
        btn_openDialog_Grundplatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_openDialog_GrundplatteActionPerformed(evt);
            }
        });
        jPanel_editLabels.add(btn_openDialog_Grundplatte);

        btn_delete_Grundplatte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Löschen.png"))); // NOI18N
        btn_delete_Grundplatte.setEnabled(false);
        btn_delete_Grundplatte.setPreferredSize(new java.awt.Dimension(23, 23));
        btn_delete_Grundplatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_GrundplatteActionPerformed(evt);
            }
        });
        jPanel_editLabels.add(btn_delete_Grundplatte);

        jLabel_Druckplatte.setText("Druckplatte");
        jLabel_Druckplatte.setToolTipText("");
        jLabel_Druckplatte.setPreferredSize(new java.awt.Dimension(104, 14));
        jPanel_editLabels.add(jLabel_Druckplatte);

        btn_openDialog_Druckplatte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Lupe.png"))); // NOI18N
        btn_openDialog_Druckplatte.setEnabled(false);
        btn_openDialog_Druckplatte.setPreferredSize(new java.awt.Dimension(23, 23));
        btn_openDialog_Druckplatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_openDialog_DruckplatteActionPerformed(evt);
            }
        });
        jPanel_editLabels.add(btn_openDialog_Druckplatte);

        btn_delete_Druckplatte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Löschen.png"))); // NOI18N
        btn_delete_Druckplatte.setEnabled(false);
        btn_delete_Druckplatte.setPreferredSize(new java.awt.Dimension(23, 23));
        btn_delete_Druckplatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_DruckplatteActionPerformed(evt);
            }
        });
        jPanel_editLabels.add(btn_delete_Druckplatte);

        jPanel_editTextFields.setOpaque(false);
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0);
        flowLayout1.setAlignOnBaseline(true);
        jPanel_editTextFields.setLayout(flowLayout1);

        jTextField_key.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField_key.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextField_key.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTextField_key.setEnabled(false);
        jTextField_key.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel_editTextFields.add(jTextField_key);

        jFormattedTextField_Bezeichnung.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(1, 2, 1, 2)));
        jFormattedTextField_Bezeichnung.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFormattedTextField_Bezeichnung.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jFormattedTextField_Bezeichnung.setEnabled(false);
        jFormattedTextField_Bezeichnung.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel_editTextFields.add(jFormattedTextField_Bezeichnung);

        jTextArea_Beschreibung.setColumns(18);
        jTextArea_Beschreibung.setLineWrap(true);
        jTextArea_Beschreibung.setRows(3);
        jTextArea_Beschreibung.setWrapStyleWord(true);
        jTextArea_Beschreibung.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(1, 2, 1, 2)));
        jTextArea_Beschreibung.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTextArea_Beschreibung.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea_Beschreibung);

        jPanel_editTextFields.add(jScrollPane1);

        jFormattedTextField_Druckrahmen.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(1, 2, 1, 2)));
        jFormattedTextField_Druckrahmen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextField_Druckrahmen.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jFormattedTextField_Druckrahmen.setEnabled(false);
        jFormattedTextField_Druckrahmen.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel_editTextFields.add(jFormattedTextField_Druckrahmen);

        jFormattedTextField_Segmentrahmen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextField_Segmentrahmen.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(1, 2, 1, 2)));
        jFormattedTextField_Segmentrahmen.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jFormattedTextField_Segmentrahmen.setEnabled(false);
        jFormattedTextField_Segmentrahmen.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel_editTextFields.add(jFormattedTextField_Segmentrahmen);

        jFormattedTextField_Unterbauleiste.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextField_Unterbauleiste.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(1, 2, 1, 2)));
        jFormattedTextField_Unterbauleiste.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jFormattedTextField_Unterbauleiste.setEnabled(false);
        jFormattedTextField_Unterbauleiste.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel_editTextFields.add(jFormattedTextField_Unterbauleiste);

        jFormattedTextField_Kühlplatte.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextField_Kühlplatte.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(1, 2, 1, 2)));
        jFormattedTextField_Kühlplatte.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jFormattedTextField_Kühlplatte.setEnabled(false);
        jFormattedTextField_Kühlplatte.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel_editTextFields.add(jFormattedTextField_Kühlplatte);

        jFormattedTextField_Grundplatte.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextField_Grundplatte.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(1, 2, 1, 2)));
        jFormattedTextField_Grundplatte.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jFormattedTextField_Grundplatte.setEnabled(false);
        jFormattedTextField_Grundplatte.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel_editTextFields.add(jFormattedTextField_Grundplatte);

        jFormattedTextField_Druckplatte.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextField_Druckplatte.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(1, 2, 1, 2)));
        jFormattedTextField_Druckplatte.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jFormattedTextField_Druckplatte.setEnabled(false);
        jFormattedTextField_Druckplatte.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel_editTextFields.add(jFormattedTextField_Druckplatte);

        btn_new.setText("Neu");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        btn_edit.setText("Bearbeiten");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_delete.setText("Löschen");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_accept.setText("Übernehmen");
        btn_accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_acceptActionPerformed(evt);
            }
        });

        btn_cancel.setText("Abbrechen");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_duplicate.setText("Duplizieren");
        btn_duplicate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_duplicateActionPerformed(evt);
            }
        });

        lbl_Anlagedatum.setText("Anlagedatum:");
        lbl_Anlagedatum.setEnabled(false);
        lbl_Anlagedatum.setPreferredSize(new java.awt.Dimension(120, 20));

        lbl_Änderungsdatum.setText("Änderungsdatum:");
        lbl_Änderungsdatum.setEnabled(false);
        lbl_Änderungsdatum.setPreferredSize(new java.awt.Dimension(120, 20));

        lbl_Benutzer.setText("Benutzer:");
        lbl_Benutzer.setEnabled(false);
        lbl_Benutzer.setPreferredSize(new java.awt.Dimension(120, 20));

        jTextField_Anlagedatum.setEditable(false);
        jTextField_Anlagedatum.setBorder(null);
        jTextField_Anlagedatum.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTextField_Anlagedatum.setEnabled(false);
        jTextField_Anlagedatum.setOpaque(false);
        jTextField_Anlagedatum.setPreferredSize(new java.awt.Dimension(204, 20));

        jTextField_Änderungsdatum.setEditable(false);
        jTextField_Änderungsdatum.setBorder(null);
        jTextField_Änderungsdatum.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTextField_Änderungsdatum.setEnabled(false);
        jTextField_Änderungsdatum.setOpaque(false);
        jTextField_Änderungsdatum.setPreferredSize(new java.awt.Dimension(204, 20));

        jTextField_Benutzer.setEditable(false);
        jTextField_Benutzer.setBorder(null);
        jTextField_Benutzer.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTextField_Benutzer.setEnabled(false);
        jTextField_Benutzer.setOpaque(false);
        jTextField_Benutzer.setPreferredSize(new java.awt.Dimension(204, 20));

        javax.swing.GroupLayout jPanel_editDataLayout = new javax.swing.GroupLayout(jPanel_editData);
        jPanel_editData.setLayout(jPanel_editDataLayout);
        jPanel_editDataLayout.setHorizontalGroup(
            jPanel_editDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_editDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_editDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_editDataLayout.createSequentialGroup()
                        .addComponent(btn_accept)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cancel)
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_editDataLayout.createSequentialGroup()
                        .addComponent(btn_new)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_edit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_duplicate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_delete)))
                .addGap(56, 56, 56)
                .addGroup(jPanel_editDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Benutzer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Anlagedatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Änderungsdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_editDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_Anlagedatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Änderungsdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Benutzer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel_editLabels, javax.swing.GroupLayout.DEFAULT_SIZE, 2527, Short.MAX_VALUE)
            .addComponent(jPanel_editTextFields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_editDataLayout.setVerticalGroup(
            jPanel_editDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_editDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_editLabels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_editTextFields, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_editDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_editDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_editDataLayout.createSequentialGroup()
                            .addComponent(lbl_Anlagedatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbl_Änderungsdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbl_Benutzer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel_editDataLayout.createSequentialGroup()
                            .addComponent(jTextField_Anlagedatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField_Änderungsdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField_Benutzer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_editDataLayout.createSequentialGroup()
                        .addGroup(jPanel_editDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_new)
                            .addComponent(btn_edit)
                            .addComponent(btn_delete)
                            .addComponent(btn_duplicate))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel_editDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_accept)
                            .addComponent(btn_cancel))))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jScrollPane_editData.setViewportView(jPanel_editData);

        javax.swing.GroupLayout jPanel_baseLayout = new javax.swing.GroupLayout(jPanel_base);
        jPanel_base.setLayout(jPanel_baseLayout);
        jPanel_baseLayout.setHorizontalGroup(
            jPanel_baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_baseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_editData)
                .addContainerGap())
            .addGroup(jPanel_baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_baseLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel_footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
                .addComponent(jPanel_table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_baseLayout.setVerticalGroup(
            jPanel_baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_baseLayout.createSequentialGroup()
                .addContainerGap(378, Short.MAX_VALUE)
                .addComponent(jScrollPane_editData, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(jPanel_baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_baseLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel_table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(228, 228, 228)
                    .addComponent(jPanel_footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getDBConnection() { 
        MY_DBCM = new DB_ConnectionManager("jdbc:sqlserver://HV-ABAS-SQL;databaseName=DiafBDE;integratedSecurity=true", "CONNECT");
        if (!MY_DBCM.isConnnected()) {
            JOptionPane.showMessageDialog(null,
                    "Der Verbindungs-Aufbau zur Datenbank ist gescheitert. Bitte wenden Sie sich an den Entwickler.",
                    "Fehler",
                    JOptionPane.ERROR_MESSAGE);
        }        
    }
   
    private void get_DBTableData() {        
        try
        { 
            MY_DBCM.setConnection_CLOSED("jdbc:sqlserver://HV-ABAS-SQL;databaseName=DiafBDE;integratedSecurity=true", "DISCONNECT");
            MY_DBCM = new DB_ConnectionManager("jdbc:sqlserver://HV-ABAS-SQL;databaseName=DiafBDE;integratedSecurity=true", "CONNECT");
            myConnection = MY_DBCM.getConnection();
            Statement myStatement = myConnection.createStatement();
            String mySQL = "SELECT * FROM DiafBDE.dbo.T_Grundformstamm";
            ResultSet myResultSet = myStatement.executeQuery(mySQL);            
            TableColumns = myResultSet.getMetaData().getColumnCount();
            myTableModel = (DefaultTableModel) jTable_dbData.getModel();
            int allOldRows = myTableModel.getRowCount();
            if (allOldRows > 0) {
                myTableModel.setRowCount(0);
            }
            while (myResultSet.next()) {
                  
                String[] myValue = new String[TableColumns];
                SimpleDateFormat myFormat = new SimpleDateFormat("dd.MM.yyyy HH:mm:ss");
                for (int i = 1; i <= TableColumns; i++) {
                          
                    String myDataSet = myResultSet.getString(i);
//                    System.out.println(myDataSet);
//                    ---------------------
//                    if (myDataSet != null && i == 5) {
//                        if (myDataSet.equals("1")) {
//                            myValue[5] = "hart";
//                        }
//                        else {myValue[5] = "weich";}
//                    }
//                    ---------------------
                    if (myDataSet != null && i == 10 || myDataSet != null && i == 11) {
                        Timestamp ts = Timestamp.valueOf(myDataSet);
                        myDataSet = myFormat.format(ts);
                    }
//                    if (i <= 5){myValue[i-1] = myDataSet;}
//                    else {myValue[i] = myDataSet;}
                        myValue[i-1] = myDataSet;
                }  
                myTableModel.addRow(myValue); 
            }
            if (!myResultSet.next()) {
                
            } 
        }
        catch (SQLException myException )
        {
            System.out.println(myException);
        }
        finally {
            try {                
                set_textFieldsEmpty(); 
                if (myConnection != null && !myConnection.isClosed()) {
                    myConnection.close();
                }
            } catch (SQLException myException) {
                System.out.println(myException);
            }
        }
    }
    
    private String get_dependentValueFromDB(String aKey) {        
        try
        { 
            MY_DBCM.setConnection_CLOSED("jdbc:sqlserver://HV-ABAS-SQL;databaseName=DiafBDE;integratedSecurity=true", "DISCONNECT");
            MY_DBCM = new DB_ConnectionManager("jdbc:sqlserver://HV-ABAS-SQL;databaseName=DiafBDE;integratedSecurity=true", "CONNECT");
            myConnection = MY_DBCM.getConnection();
            Statement myStatement = myConnection.createStatement();
            String mySQL = "SELECT * FROM DiafBDE.dbo.T_Säulengestell Where pKey_GF = '" + aKey + "'";
            ResultSet myResultSet = myStatement.executeQuery(mySQL);            
            int myColumns = myResultSet.getMetaData().getColumnCount();
//            myTableModel = (DefaultTableModel) jTable_dbData.getModel();
//            int allOldRows = myTableModel.getRowCount();
//            if (allOldRows > 0) {
//                myTableModel.setRowCount(0);
//            }
            while (myResultSet.next()) {
                  
                String[] myValue = new String[myColumns];
//                SimpleDateFormat myFormat = new SimpleDateFormat("dd.MM.yyyy HH:mm:ss");
                for (int i = 1; i <= myColumns; i++) {
                          
                    String myDataSet = myResultSet.getString(i);
//                    System.out.println(myDataSet);
//                    ---------------------
//                    if (myDataSet != null && i == 5) {
//                        if (myDataSet.equals("1")) {
//                            myValue[5] = "hart";
//                        }
//                        else {myValue[5] = "weich";}
//                    }
//                    ---------------------
//                    if (myDataSet != null && i == 4 || myDataSet != null && i == 5) {
//                        Timestamp ts = Timestamp.valueOf(myDataSet);
//                        myDataSet = myFormat.format(ts);
//                    }
//                    if (i <= 5){myValue[i-1] = myDataSet;}
//                    else {myValue[i] = myDataSet;}
                        myValue[i-1] = myDataSet;
                }  
//                myTableModel.addRow(myValue); 
                MyDependentValue_Bezeichnung = myValue[1];
            }
            if (!myResultSet.next()) {
                
            } 
        }
        catch (SQLException myException )
        {
            System.out.println(myException);
        }
        finally {
            try {  
                if (myConnection != null && !myConnection.isClosed()) {
                    myConnection.close();
                }
            } catch (SQLException myException) {
                System.out.println(myException);
            }
        }
        return MyDependentValue_Bezeichnung;
    }
    private void jTextField_searchValueKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_searchValueKeyReleased
        // TODO add your handling code here:
        search();
        lbl_rowCount.setText(String.valueOf(mySorter.getViewRowCount()) + " von " + String.valueOf(myTableModel.getRowCount()));
    }//GEN-LAST:event_jTextField_searchValueKeyReleased

    private void btn_deleteSearchValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteSearchValueActionPerformed
        // TODO add your handling code here:
        jTextField_searchValue.setText("");
        search();
        lbl_rowCount.setText(String.valueOf(mySorter.getViewRowCount()) + " von " + String.valueOf(myTableModel.getRowCount()));
    }//GEN-LAST:event_btn_deleteSearchValueActionPerformed

    private void btn_getCurrentDBDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_getCurrentDBDataActionPerformed
        // TODO add your handling code here:
        get_DBTableData();
        btn_new.setEnabled(true);
        btn_edit.setEnabled(false);
        btn_duplicate.setEnabled(false);
        btn_delete.setEnabled(false);
        btn_accept.setEnabled(false);
        btn_cancel.setEnabled(false);
    }//GEN-LAST:event_btn_getCurrentDBDataActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:
        if (MY_DBCM.isConnnected()) {
            MY_DBCM.setConnection_CLOSED("jdbc:sqlserver://HV-ABAS-SQL;databaseName=DiafBDE;integratedSecurity=true", "DISCONNECT");
        }
        int myReturnValue = test_continueEditing();
        if (myReturnValue != 0 || DataSet_Mode.equals("clean")) {
            InstanceCount = 0;
            this.dispose();
        }
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_openDialog_DruckrahmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_openDialog_DruckrahmenActionPerformed
        // TODO add your handling code here:
        Dialog_DataUse_Druckrahmen myDialog = new Dialog_DataUse_Druckrahmen(this,true); //noch ändern!!!
        myDialog.setTitle("Druckrahmen");
        //        Point location = MouseInfo.getPointerInfo().getLocation();
        //        myDialog.setLocation(Toolkit.getDefaultToolkit().getScreenSize().width / 2 , Toolkit.getDefaultToolkit().getScreenSize().height / 2);
        myDialog.setLocationRelativeTo(null);
        myDialog.setVisible(true);
        String resultFromDialog_ID = myDialog.getChoosenDruckrahmen_ID();
        if (!resultFromDialog_ID.equals("")) {
            this.jFormattedTextField_Druckrahmen.setText(resultFromDialog_ID);
        }
    }//GEN-LAST:event_btn_openDialog_DruckrahmenActionPerformed

    private void btn_delete_DruckrahmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_DruckrahmenActionPerformed
        // TODO add your handling code here:
        jFormattedTextField_Druckrahmen.setText("");
    }//GEN-LAST:event_btn_delete_DruckrahmenActionPerformed

    private void btn_openDialog_SegmentrahmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_openDialog_SegmentrahmenActionPerformed
        // TODO add your handling code here:
        Dialog_DataUse_Segmentrahmen myDialog = new Dialog_DataUse_Segmentrahmen(this,true); //noch ändern!!!
        myDialog.setTitle("Segmentrahmen");
        //        Point location = MouseInfo.getPointerInfo().getLocation();
        //        myDialog.setLocation(Toolkit.getDefaultToolkit().getScreenSize().width / 2 , Toolkit.getDefaultToolkit().getScreenSize().height / 2);
        myDialog.setLocationRelativeTo(null);
        myDialog.setVisible(true);
        String resultFromDialog_ID = myDialog.getChoosenSegmentrahmen_ID();
        if (!resultFromDialog_ID.equals("")) {
            this.jFormattedTextField_Segmentrahmen.setText(resultFromDialog_ID);
        }
    }//GEN-LAST:event_btn_openDialog_SegmentrahmenActionPerformed

    private void btn_delete_SegmentrahmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_SegmentrahmenActionPerformed
        // TODO add your handling code here:
        jFormattedTextField_Segmentrahmen.setText("");
    }//GEN-LAST:event_btn_delete_SegmentrahmenActionPerformed

    private void btn_openDialog_UnterbauleisteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_openDialog_UnterbauleisteActionPerformed
        // TODO add your handling code here:
        Dialog_DataUse_Unterbauleiste myDialog = new Dialog_DataUse_Unterbauleiste(this,true); //noch ändern!!!
        myDialog.setTitle("Unterbauleiste");
        myDialog.setLocationRelativeTo(null);
        myDialog.setVisible(true);
        String resultFromDialog_ID = myDialog.getChoosenUnterbauleisten_ID();
        if (!resultFromDialog_ID.equals("")) {
            this.jFormattedTextField_Unterbauleiste.setText(resultFromDialog_ID);
        }
    }//GEN-LAST:event_btn_openDialog_UnterbauleisteActionPerformed

    private void btn_delete_UnterbauleisteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_UnterbauleisteActionPerformed
        // TODO add your handling code here:
        jFormattedTextField_Unterbauleiste.setText("");
    }//GEN-LAST:event_btn_delete_UnterbauleisteActionPerformed

    private void btn_openDialog_KühlplatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_openDialog_KühlplatteActionPerformed
        // TODO add your handling code here:
        Dialog_DataUse_Kühlplatte myDialog = new Dialog_DataUse_Kühlplatte(this,true); //noch ändern!!!
        myDialog.setTitle("Kühlplatte");
        myDialog.setLocationRelativeTo(null);
        myDialog.setVisible(true);
        String resultFromDialog_ID = myDialog.getChoosenKühlplatten_ID();
        if (!resultFromDialog_ID.equals("")) {
            this.jFormattedTextField_Kühlplatte.setText(resultFromDialog_ID);
        }
    }//GEN-LAST:event_btn_openDialog_KühlplatteActionPerformed

    private void btn_delete_KühlplatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_KühlplatteActionPerformed
        // TODO add your handling code here:
        jFormattedTextField_Kühlplatte.setText("");
    }//GEN-LAST:event_btn_delete_KühlplatteActionPerformed

    private void btn_openDialog_GrundplatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_openDialog_GrundplatteActionPerformed
        // TODO add your handling code here:
        Dialog_DataUse_Grundplatte myDialog = new Dialog_DataUse_Grundplatte(this,true); //noch ändern!!!
        myDialog.setTitle("Grundplatte");
        //        Point location = MouseInfo.getPointerInfo().getLocation();
        //        myDialog.setLocation(location.x + 20 , location.y - 300);
        myDialog.setLocationRelativeTo(null);
        myDialog.setVisible(true);
        String resultFromDialog_ID = myDialog.getChoosenGrundplatten_ID();
        if (!resultFromDialog_ID.equals("")) {
            this.jFormattedTextField_Grundplatte.setText(resultFromDialog_ID);
        }
    }//GEN-LAST:event_btn_openDialog_GrundplatteActionPerformed

    private void btn_delete_GrundplatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_GrundplatteActionPerformed
        // TODO add your handling code here:
        jFormattedTextField_Grundplatte.setText("");
    }//GEN-LAST:event_btn_delete_GrundplatteActionPerformed

    private void btn_openDialog_DruckplatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_openDialog_DruckplatteActionPerformed
        // TODO add your handling code here:
        Dialog_DataUse_Druckplatte myDialog = new Dialog_DataUse_Druckplatte(this,true); //noch ändern!!!
        myDialog.setTitle("Druckplatte");
        myDialog.setLocationRelativeTo(null);
        myDialog.setVisible(true);
        String resultFromDialog_ID = myDialog.getChoosenDruckplatten_ID();
        if (!resultFromDialog_ID.equals("")) {
            this.jFormattedTextField_Druckplatte.setText(resultFromDialog_ID);
        }
    }//GEN-LAST:event_btn_openDialog_DruckplatteActionPerformed

    private void btn_delete_DruckplatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_DruckplatteActionPerformed
        // TODO add your handling code here:
        jFormattedTextField_Druckplatte.setText("");
    }//GEN-LAST:event_btn_delete_DruckplatteActionPerformed

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        // TODO add your handling code here:
        DataSet_Mode = "new";
        set_textFieldsEnabled(true);
        set_oldValues();
        set_tableEnabled(false);
        set_buttonsEnabled(true);
        set_textFieldsEmpty();
        jTextField_key.setText("GF");
        jTextField_key.requestFocus();
        btn_new.setEnabled(false);
        btn_edit.setEnabled(false);
        btn_duplicate.setEnabled(false);
        btn_delete.setEnabled(false);
        btn_accept.setEnabled(true);
        btn_cancel.setEnabled(true);
        //        btn_openDialog_Grundform.setEnabled(true);
    }//GEN-LAST:event_btn_newActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        DataSet_Mode = "edit";
        set_oldValues();
        set_tableEnabled(false);
        set_textFieldsEnabled(true);
        set_buttonsEnabled(true);
        jFormattedTextField_Bezeichnung.requestFocus();
        btn_new.setEnabled(false);
        btn_edit.setEnabled(false);
        btn_duplicate.setEnabled(false);
        btn_delete.setEnabled(false);
        btn_accept.setEnabled(true);
        btn_cancel.setEnabled(true);
        btn_openDialog_Segmentrahmen.setEnabled(true);
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        DataSet_Mode = "delete";
        if (DataSet_Mode.equals("delete") && test_isDataSetInDB(jTextField_key.getText().trim()) == true) {
            int myAnswer = JOptionPane.showConfirmDialog(null,
                "Soll der Datensatz GF (Key): \n\n >> " + jTextField_key.getText().trim() + " << \n\n wirklich gelöscht werden?",
                "Datensatz löschen?",
                JOptionPane.YES_NO_OPTION);
            if (myAnswer == 0) {
                do_deleteDataSet_inDB();
                get_DBTableData();
                //                set_textFieldsDisabled();
                btn_new.setEnabled(true);
                btn_edit.setEnabled(false);
                btn_duplicate.setEnabled(false);
                btn_delete.setEnabled(false);
                btn_accept.setEnabled(false);
                btn_cancel.setEnabled(false);
                lbl_rowCount.setText(String.valueOf(mySorter.getViewRowCount()) + " von " + String.valueOf(myTableModel.getRowCount()));
            }
        }
        DataSet_Mode = "clean";
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_acceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_acceptActionPerformed
        // TODO add your handling code here:
        if (jTextField_key.getText().isEmpty() || jTextField_key.getText().equals("GF")) {
            JOptionPane.showMessageDialog(null,
                "Der Datensatz ist teilweise leer. Erfassen Sie Daten oder klicken Sie auf Abbrechen.",
                "Fehler",
                JOptionPane.ERROR_MESSAGE);
        }
        else {
            boolean myAnswer = test_isDataSetInDB(jTextField_key.getText().trim());

            if (myAnswer == true) {
                if (DataSet_Mode.equals("new")) {
                    JOptionPane.showMessageDialog(null,
                        "Es existiert schon ein Datensatz mit diesem Key: \n\n >> " + jTextField_key.getText().trim() + " <<.",
                        "Fehler",
                        JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if (DataSet_Mode.equals("edit")  && !Old_Bezeichnung.equals(jFormattedTextField_Bezeichnung.getText().trim())
                    || !Old_Beschreibung.equals(jTextArea_Beschreibung.getText().trim())
                    || !Old_Druckrahmen.equals(jFormattedTextField_Druckrahmen.getText().trim())
                    || !Old_Segmentrahmen.equals(jFormattedTextField_Segmentrahmen.getText().trim())
                    || !Old_Unterbauleiste.equals(jFormattedTextField_Unterbauleiste.getText().trim())
                    || !Old_Kühlplatte.equals(jFormattedTextField_Kühlplatte.getText().trim())
                    || !Old_Grundplatte.equals(jFormattedTextField_Grundplatte.getText().trim())
                    || !Old_Druckplatte.equals(jFormattedTextField_Druckplatte.getText().trim())) {
                    do_updateDataSet_inDB();
                }
                if (DataSet_Mode.equals("duplicate")) {
                    JOptionPane.showMessageDialog(null,"Beim Duplizieren muss ein neuer Key vergeben werden.",
                        "Fehler",
                        JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            if (myAnswer == false) {
                if (DataSet_Mode.equals("new") || DataSet_Mode.equals("duplicate")) {
                    do_insertDataSet_intoDB();
                }
            }
            set_textFieldsEnabled(false);
            set_buttonsEnabled(false);
            btn_new.setEnabled(true);
            btn_accept.setEnabled(false);
            btn_cancel.setEnabled(false);
            btn_openDialog_Segmentrahmen.setEnabled(false);
            btn_delete_Segmentrahmen.setEnabled(false);
            //            if (jTable_dbData.getSelectedRow() > -1) {
                //
                //                btn_edit.setEnabled(true);
                //                btn_duplicate.setEnabled(true);
                //                btn_delete.setEnabled(true);
                //            }
            //            else {
                btn_edit.setEnabled(false);
                btn_duplicate.setEnabled(false);
                btn_delete.setEnabled(false);
                set_tableEnabled(true);
                //            }
            get_DBTableData();
            lbl_rowCount.setText(String.valueOf(mySorter.getViewRowCount()) + " von " + String.valueOf(myTableModel.getRowCount()));
            DataSet_Mode = "clean";
        }
    }//GEN-LAST:event_btn_acceptActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        get_oldValues();
        //        set_textFieldsDisabled();
        btn_new.setEnabled(true);
        if (!Old_Key.equals("")) {
            btn_edit.setEnabled(true);
            btn_duplicate.setEnabled(true);
            btn_delete.setEnabled(true);
        }
        btn_accept.setEnabled(false);
        btn_cancel.setEnabled(false);
        btn_openDialog_Segmentrahmen.setEnabled(false);
        btn_delete_Segmentrahmen.setEnabled(false);
        set_tableEnabled(true);
        set_buttonsEnabled(false);
        set_textFieldsEnabled(false);
        DataSet_Mode = "clean";
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_duplicateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_duplicateActionPerformed
        // TODO add your handling code here:
        DataSet_Mode = "duplicate";
        set_oldValues();
        set_tableEnabled(false);
        set_textFieldsEnabled(true);
        set_buttonsEnabled(true);
        jTextField_key.requestFocus();
        btn_new.setEnabled(false);
        btn_edit.setEnabled(false);
        btn_duplicate.setEnabled(false);
        btn_delete.setEnabled(false);
        btn_accept.setEnabled(true);
        btn_cancel.setEnabled(true);
        btn_openDialog_Segmentrahmen.setEnabled(true);
    }//GEN-LAST:event_btn_duplicateActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        do_preBuild();
        do_postBuild();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int myReturnValue = test_continueEditing();
            if (myReturnValue != 0) {
                this.dispose();
            }
    }//GEN-LAST:event_formWindowClosing

    private int test_continueEditing() {
        int myAnswer = 0;
        if (!DataSet_Mode.equals("clean")) {

            myAnswer = JOptionPane.showOptionDialog(null, 
            "Es existieren noch ungespeicherte Änderungenn. \n Möchten Sie die Bearbeitung fortsetzen oder das Fenster schließen?", 
            "Bearbeitung fortsetzen?", 
            JOptionPane.OK_CANCEL_OPTION, 
            JOptionPane.INFORMATION_MESSAGE, 
            null, 
            new String[]{"Bearbeitung fortsetzen", "Fenster schließen"},
            "default");
            }
        return myAnswer;
    }
    
    private void set_textFieldsEmpty() {
        jTextField_key.setText("");
        jFormattedTextField_Bezeichnung.setText("");
        jTextArea_Beschreibung.setText("");
        jFormattedTextField_Druckrahmen.setText("");
        jFormattedTextField_Segmentrahmen.setText("");
        jFormattedTextField_Unterbauleiste.setText("");
        jFormattedTextField_Kühlplatte.setText("");
        jFormattedTextField_Grundplatte.setText("");
        jFormattedTextField_Druckplatte.setText("");
        jTextField_Anlagedatum.setText("");
        jTextField_Änderungsdatum.setText("");
        jTextField_Benutzer.setText("");      
    }
    
    private void set_oldValues() {         
        Old_Key = jTextField_key.getText().trim();
        Old_Bezeichnung = jFormattedTextField_Bezeichnung.getText().trim();
        Old_Beschreibung = jTextArea_Beschreibung.getText().trim();
        Old_Druckrahmen = jFormattedTextField_Druckrahmen.getText().trim();
        Old_Segmentrahmen = jFormattedTextField_Segmentrahmen.getText().trim();
        Old_Unterbauleiste = jFormattedTextField_Unterbauleiste.getText().trim();
        Old_Kühlplatte = jFormattedTextField_Kühlplatte.getText().trim();
        Old_Grundplatte = jFormattedTextField_Grundplatte.getText().trim();
        Old_Druckplatte = jFormattedTextField_Druckplatte.getText().trim();
        Old_Anlagedatum = jTextField_Anlagedatum.getText();
        Old_Änderungsdatum = jTextField_Änderungsdatum.getText();
        Old_Benutzer = jTextField_Benutzer.getText();
    }
    
    private void get_oldValues() {         
        jTextField_key.setText(Old_Key);
        jFormattedTextField_Bezeichnung.setText(Old_Bezeichnung);
        jTextArea_Beschreibung.setText(Old_Beschreibung);
        jFormattedTextField_Druckrahmen.setText(Old_Druckrahmen); 
        jFormattedTextField_Segmentrahmen.setText(Old_Segmentrahmen); 
        jFormattedTextField_Unterbauleiste.setText(Old_Unterbauleiste); 
        jFormattedTextField_Kühlplatte.setText(Old_Kühlplatte); 
        jFormattedTextField_Grundplatte.setText(Old_Grundplatte); 
        jFormattedTextField_Druckplatte.setText(Old_Druckplatte); 
        jTextField_Anlagedatum.setText(Old_Anlagedatum);
        jTextField_Änderungsdatum.setText(Old_Änderungsdatum);
        jTextField_Benutzer.setText(Old_Benutzer);
    }
    
    private void set_textFieldsEnabled(boolean aBoolean) {  
        
        for (int i=1; i < jPanel_editTextFields.getComponentCount(); i++) {
            jPanel_editTextFields.getComponent(i).setEnabled(aBoolean);
        }
        jTextField_key.setEnabled(aBoolean);
        jFormattedTextField_Bezeichnung.setEnabled(true);
        jTextArea_Beschreibung.setEnabled(true);
    }
        
    private void set_buttonsEnabled(boolean aBoolean) {
              
//        for (int i=0; i < jPanel_editLabels.getComponentCount(); i++) {
//            if (jPanel_editLabels.getComponent(i).getName().substring(1, 4).equals("btn_")) {
//                    jPanel_editLabels.getComponent(i).setEnabled(aBoolean);
//            }
//        }
        btn_openDialog_Druckrahmen.setEnabled(aBoolean);
        btn_delete_Druckrahmen.setEnabled(aBoolean);
        btn_openDialog_Segmentrahmen.setEnabled(aBoolean);
        btn_delete_Segmentrahmen.setEnabled(aBoolean);
        btn_openDialog_Unterbauleiste.setEnabled(aBoolean);
        btn_delete_Unterbauleiste.setEnabled(aBoolean);
        btn_openDialog_Kühlplatte.setEnabled(aBoolean);
        btn_delete_Kühlplatte.setEnabled(aBoolean);
        btn_openDialog_Grundplatte.setEnabled(aBoolean);
        btn_delete_Grundplatte.setEnabled(aBoolean);
        btn_openDialog_Druckplatte.setEnabled(aBoolean);
        btn_delete_Druckplatte.setEnabled(aBoolean);
    }
    
    private boolean test_isDataSetInDB(String aString) {
        boolean myAnswer = false;
        for (int myRow = 0; myRow < jTable_dbData.getRowCount(); ++myRow ) {
            if (myTableModel.getValueAt(myRow, 0).toString().trim().equals(aString))
                myAnswer = true;           
        }
        return myAnswer;
    }
    
    private void do_deleteDataSet_inDB() {        
        try
        {
            MY_DBCM.setConnection_CLOSED("jdbc:sqlserver://HV-ABAS-SQL;databaseName=DiafBDE;integratedSecurity=true", "DISCONNECT");
            MY_DBCM = new DB_ConnectionManager("jdbc:sqlserver://HV-ABAS-SQL;databaseName=DiafBDE;integratedSecurity=true", "CONNECT");
            if (MY_DBCM.isConnnected()) 
            {   
            myConnection = MY_DBCM.getConnection();
            Statement myStatement = myConnection.createStatement();
            myStatement.executeUpdate("DELETE FROM DiafBDE.dbo.T_Grundformstamm WHERE pKey_GF = '" + jTextField_key.getText().trim() + "'");             
            }   
        }
        catch (/*ClassNotFoundException |*/ SQLException myException )
        {
        }
        finally {
            try {
                if (myConnection != null && !myConnection.isClosed()) {
                    myConnection.close();
                }
            } catch (SQLException myException) {
            }
        }                  
    }
    
    private void do_updateDataSet_inDB() {        
        try
        {
            MY_DBCM.setConnection_CLOSED("jdbc:sqlserver://HV-ABAS-SQL;databaseName=DiafBDE;integratedSecurity=true", "DISCONNECT");
            MY_DBCM = new DB_ConnectionManager("jdbc:sqlserver://HV-ABAS-SQL;databaseName=DiafBDE;integratedSecurity=true", "CONNECT");
            if (MY_DBCM.isConnnected()) 
            {   
            myConnection = MY_DBCM.getConnection();
            SimpleDateFormat myFormat = new SimpleDateFormat("dd.MM.yyyy HH:mm:ss");
            Änderungsdatum = new Timestamp(System.currentTimeMillis());
            String result = myFormat.format(Änderungsdatum);
            Benutzer = System.getProperty("user.name"); 
            Statement myStatement = myConnection.createStatement();
            myStatement.executeUpdate("UPDATE DiafBDE.dbo.T_Grundformstamm SET Bezeichnung = '" + jFormattedTextField_Bezeichnung.getText().trim() +
                    "', Beschreibung = '" + jTextArea_Beschreibung.getText().trim() +
                    "', Druckrahmen = '" + jFormattedTextField_Druckrahmen.getText().trim() +
                    "', Segmentrahmen = '" + jFormattedTextField_Segmentrahmen.getText().trim() +
                    "', Unterbauleiste = '" + jFormattedTextField_Unterbauleiste.getText().trim() +
                    "', Kühlplatte = '" + jFormattedTextField_Kühlplatte.getText().trim() +
                    "', Grundplatte = '" + jFormattedTextField_Grundplatte.getText().trim() +
                    "', Druckplatte = '" + jFormattedTextField_Druckplatte.getText().trim() +
                    "', Änderungsdatum = '" + result +
                    "', Benutzer = '" + Benutzer +
                    
                    "' WHERE pKey_GF = '" + jTextField_key.getText() + "'");             
            } 
        }
        catch (/*ClassNotFoundException |*/ SQLException myException )
        {
        }
        finally {
            try {
                if (myConnection != null && !myConnection.isClosed()) {
                    myConnection.close();
                }
            } catch (SQLException myException) {
            }
        }   
    }
    
    private void do_insertDataSet_intoDB() {        
        try
        {
//            System.out.println(((Number) jFormattedTextField_value2.getValue()).floatValue());
            MY_DBCM.setConnection_CLOSED("jdbc:sqlserver://HV-ABAS-SQL;databaseName=DiafBDE;integratedSecurity=true", "DISCONNECT");
            MY_DBCM = new DB_ConnectionManager("jdbc:sqlserver://HV-ABAS-SQL;databaseName=DiafBDE;integratedSecurity=true", "CONNECT");
            if (MY_DBCM.isConnnected()) 
            {    
            myConnection = MY_DBCM.getConnection();
            SimpleDateFormat myFormat = new SimpleDateFormat("dd.MM.yyyy HH:mm:ss");
            Anlagedatum = new Timestamp(System.currentTimeMillis());
            String result = myFormat.format(Anlagedatum);
            Benutzer = System.getProperty("user.name");
            if (jFormattedTextField_Druckrahmen.getText().trim().equals("")) {
                jFormattedTextField_Druckrahmen.setText("DR0");
            }
            if (jFormattedTextField_Segmentrahmen.getText().trim().equals("")) {
                jFormattedTextField_Segmentrahmen.setText("SR0");
            }
            if (jFormattedTextField_Unterbauleiste.getText().trim().equals("")) {
                jFormattedTextField_Unterbauleiste.setText("UBL0");
            }
            if (jFormattedTextField_Kühlplatte.getText().trim().equals("")) {
                jFormattedTextField_Kühlplatte.setText("KPL0");
            }
            if (jFormattedTextField_Grundplatte.getText().trim().equals("")) {
                jFormattedTextField_Grundplatte.setText("GPL0");
            }
            if (jFormattedTextField_Druckplatte.getText().trim().equals("")) {
                jFormattedTextField_Druckplatte.setText("DPL0");
            }
            Statement myStatement = myConnection.createStatement();
            myStatement.executeUpdate("INSERT INTO DiafBDE.dbo.T_Grundformstamm (pKey_GF, Bezeichnung, Beschreibung, Druckrahmen, Segmentrahmen, Unterbauleiste, "
                    + "Kühlplatte, Grundplatte, Druckplatte, Anlagedatum, Benutzer)" 
                    + "VALUES ('" + jTextField_key.getText().trim() + "', '" 
                    + jFormattedTextField_Bezeichnung.getText().trim() + "', '" 
                    + jTextArea_Beschreibung.getText().trim() + "', '" 
                    + jFormattedTextField_Druckrahmen.getText().trim() + "', '" 
                    + jFormattedTextField_Segmentrahmen.getText().trim() + "', '" 
                    + jFormattedTextField_Unterbauleiste.getText().trim() + "', '" 
                    + jFormattedTextField_Kühlplatte.getText().trim() + "', '" 
                    + jFormattedTextField_Grundplatte.getText().trim() + "', '" 
                    + jFormattedTextField_Druckplatte.getText().trim() + "', '" 
                    + result + "', '" 
                    + Benutzer +"')");              
            } 
        }
        catch (/*ClassNotFoundException |*/ SQLException myException )
        {
        }
        finally {
            try {
                if (myConnection != null && !myConnection.isClosed()) {
                    myConnection.close();
                }
            } catch (SQLException myException) {
            }
        }         
    }    
    
    private void set_valuesIntoTextFields() {        
//        if (!DataSet_Mode.equals("edit")) {
            OldSelection = jTable_dbData.getSelectedRow();
            if(OldSelection != -1) {
                String tempString;

                int myRow = jTable_dbData.convertRowIndexToModel(OldSelection);
                jTextField_key.setText(myTableModel.getValueAt(myRow, 0).toString().trim());

                if (myTableModel.getValueAt(myRow, 1) != null) {
                tempString = myTableModel.getValueAt(myRow, 1).toString();
                jFormattedTextField_Bezeichnung.setText(tempString);
                }
                else {jFormattedTextField_Bezeichnung.setText("");}
                
                if (myTableModel.getValueAt(myRow, 2) != null) {
                tempString = myTableModel.getValueAt(myRow, 2).toString();
                jTextArea_Beschreibung.setText(tempString);
                }
                else {jTextArea_Beschreibung.setText("");}
                
                if (myTableModel.getValueAt(myRow, 3) != null) {
                tempString = myTableModel.getValueAt(myRow, 3).toString();
                jFormattedTextField_Druckrahmen.setText(tempString);
//                jFormattedTextField_Saeulengestell_Bezeichnung.setText(this.get_dependentValueFromDB(tempString));
                }
                else {jFormattedTextField_Druckrahmen.setText("");}
                
                if (myTableModel.getValueAt(myRow, 4) != null) {
                tempString = myTableModel.getValueAt(myRow, 4).toString();
                jFormattedTextField_Segmentrahmen.setText(tempString);
                }
                else {jFormattedTextField_Segmentrahmen.setText("");}
                
                if (myTableModel.getValueAt(myRow, 5) != null) {
                tempString = myTableModel.getValueAt(myRow, 5).toString();
                jFormattedTextField_Unterbauleiste.setText(tempString);
                }
                else {jFormattedTextField_Unterbauleiste.setText("");}
                
                if (myTableModel.getValueAt(myRow, 6) != null) {
                tempString = myTableModel.getValueAt(myRow, 6).toString();
                jFormattedTextField_Kühlplatte.setText(tempString);
                }
                else {jFormattedTextField_Kühlplatte.setText("");}
                
                if (myTableModel.getValueAt(myRow, 7) != null) {
                tempString = myTableModel.getValueAt(myRow, 7).toString();
                jFormattedTextField_Grundplatte.setText(tempString);
                }
                else {jFormattedTextField_Grundplatte.setText("");}
                
                if (myTableModel.getValueAt(myRow, 8) != null) {
                tempString = myTableModel.getValueAt(myRow, 8).toString();
                jFormattedTextField_Druckplatte.setText(tempString);
                }
                else {jFormattedTextField_Druckplatte.setText("");}
                
                if (myTableModel.getValueAt(myRow, 9) != null) {
                    jTextField_Anlagedatum.setText(myTableModel.getValueAt(myRow, 9).toString().trim());
                }
                else {jTextField_Anlagedatum.setText("");}
                if (myTableModel.getValueAt(myRow, 10) != null) {
                   jTextField_Änderungsdatum.setText(myTableModel.getValueAt(myRow, 10).toString().trim());
                }
                else {jTextField_Änderungsdatum.setText("");}
                if (myTableModel.getValueAt(myRow, 11) != null) {
                    jTextField_Benutzer.setText(myTableModel.getValueAt(myRow, 11).toString().trim()); 
                }
                else {jTextField_Benutzer.setText("");}                
                
                btn_edit.setEnabled(true);
                btn_duplicate.setEnabled(true);
                btn_delete.setEnabled(true); 
            }
            else {
                btn_edit.setEnabled(false);
                btn_duplicate.setEnabled(false);
                btn_delete.setEnabled(false);
            }  
//        }        
    }
    private void set_tableEnabled(boolean aBoolean) {
        jTextField_searchValue.setEnabled(aBoolean);
        btn_deleteSearchValue.setEnabled(aBoolean);
        btn_getCurrentDBData.setEnabled(aBoolean);
        jTable_dbData.setEnabled(aBoolean);
        for (int i = 0; i < TableColumns; i ++) {
            mySorter.setSortable(i, aBoolean);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_DataMaintenance_Grundformstamm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_DataMaintenance_Grundformstamm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_DataMaintenance_Grundformstamm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_DataMaintenance_Grundformstamm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Frame_DataMaintenance_Grundformstamm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_accept;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_deleteSearchValue;
    private javax.swing.JButton btn_delete_Druckplatte;
    private javax.swing.JButton btn_delete_Druckrahmen;
    private javax.swing.JButton btn_delete_Grundplatte;
    private javax.swing.JButton btn_delete_Kühlplatte;
    private javax.swing.JButton btn_delete_Segmentrahmen;
    private javax.swing.JButton btn_delete_Unterbauleiste;
    private javax.swing.JButton btn_duplicate;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_getCurrentDBData;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_openDialog_Druckplatte;
    private javax.swing.JButton btn_openDialog_Druckrahmen;
    private javax.swing.JButton btn_openDialog_Grundplatte;
    private javax.swing.JButton btn_openDialog_Kühlplatte;
    private javax.swing.JButton btn_openDialog_Segmentrahmen;
    private javax.swing.JButton btn_openDialog_Unterbauleiste;
    private javax.swing.JFormattedTextField jFormattedTextField_Bezeichnung;
    private javax.swing.JTextField jFormattedTextField_Druckplatte;
    private javax.swing.JFormattedTextField jFormattedTextField_Druckrahmen;
    private javax.swing.JTextField jFormattedTextField_Grundplatte;
    private javax.swing.JTextField jFormattedTextField_Kühlplatte;
    private javax.swing.JTextField jFormattedTextField_Segmentrahmen;
    private javax.swing.JTextField jFormattedTextField_Unterbauleiste;
    private javax.swing.JLabel jLabel_Druckplatte;
    private javax.swing.JLabel jLabel_Grundplatte;
    private javax.swing.JLabel jLabel_Kühlplatte;
    private javax.swing.JLabel jLabel_Segmentrahmen;
    private javax.swing.JLabel jLabel_Unterbauleiste;
    private javax.swing.JPanel jPanel_base;
    private javax.swing.JPanel jPanel_editData;
    private javax.swing.JPanel jPanel_editLabels;
    private javax.swing.JPanel jPanel_editTextFields;
    private javax.swing.JPanel jPanel_footer;
    private javax.swing.JPanel jPanel_table;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane_dbData;
    private javax.swing.JScrollPane jScrollPane_editData;
    private javax.swing.JTable jTable_dbData;
    private javax.swing.JTextArea jTextArea_Beschreibung;
    private javax.swing.JTextField jTextField_Anlagedatum;
    private javax.swing.JTextField jTextField_Benutzer;
    private javax.swing.JTextField jTextField_key;
    private javax.swing.JTextField jTextField_searchValue;
    private javax.swing.JTextField jTextField_Änderungsdatum;
    private javax.swing.JLabel lbl_Anlagedatum;
    private javax.swing.JLabel lbl_Benutzer;
    private javax.swing.JLabel lbl_Beschreibung;
    private javax.swing.JLabel lbl_Bezeichnung;
    private javax.swing.JLabel lbl_Druckrahmen;
    private javax.swing.JLabel lbl_key;
    private javax.swing.JLabel lbl_rowCount;
    private javax.swing.JLabel lbl_search1;
    private javax.swing.JLabel lbl_tableName;
    private javax.swing.JLabel lbl_Änderungsdatum;
    // End of variables declaration//GEN-END:variables
}
