/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Toolkit;

/**
 *
 * @author schmidtu
 */
public class Frame_Grundform extends javax.swing.JFrame {
    static int InstanceCount;

    /**
     * Creates new form Frame_Grundform
     */
    public Frame_Grundform() {
        InstanceCount++;
        initComponents();
    }
    Frame_DataMaintenance_Druckrahmen myDMDruckrahmen;
    Frame_DataMaintenance_Segmentrahmen myDMSegmentrahmen;
    Frame_DataMaintenance_Unterbauleiste myDMUnterbauleiste;
    Frame_DataMaintenance_Kühlplatte myDMKühlplatte;
    Frame_DataMaintenance_Grundplatte myDMGrundplatte;
    Frame_DataMaintenance_Druckplatte myDMDruckplatte;
    Frame_DataMaintenance_Grundformstamm myGrundformstamm;
    
    public int getInstance() {
        return InstanceCount;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_base = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_infoAboutSequence = new javax.swing.JTextArea();
        jPanel_main = new javax.swing.JPanel();
        jPanel_buttons = new javax.swing.JPanel();
        btn_open_dataMaintenance_Druckrahmen = new javax.swing.JButton();
        btn_open_dataMaintenance_Segmentrahmen = new javax.swing.JButton();
        btn_open_dataMaintenance_Unterbauleiste = new javax.swing.JButton();
        btn_open_dataMaintenance_Kühlplatte = new javax.swing.JButton();
        btn_open_dataMaintenance_Grundplatte = new javax.swing.JButton();
        btn_open_dataMaintenance_Druckplatte = new javax.swing.JButton();
        btn_open_dataMaintenance_Grundformstamm = new javax.swing.JButton();
        btn_open_dataMaintenance_Werkzeugstamm = new javax.swing.JButton();
        jPanel_footer = new javax.swing.JPanel();
        btn_exitProgram = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setPreferredSize(new java.awt.Dimension(224, 969));

        jPanel_base.setBackground(new java.awt.Color(204, 255, 255));

        jScrollPane1.setEnabled(false);

        jTextArea_infoAboutSequence.setEditable(false);
        jTextArea_infoAboutSequence.setColumns(20);
        jTextArea_infoAboutSequence.setLineWrap(true);
        jTextArea_infoAboutSequence.setRows(5);
        jTextArea_infoAboutSequence.setText("Die Pflege der Stammdaten für die Grundform muss in einer bestimmten Reihenfolge vorgenommen werden. Die Reihenfolge ist über die Schaltflächen ersichtlich.");
        jTextArea_infoAboutSequence.setWrapStyleWord(true);
        jTextArea_infoAboutSequence.setAutoscrolls(false);
        jTextArea_infoAboutSequence.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea_infoAboutSequence);

        jPanel_main.setOpaque(false);

        jPanel_buttons.setOpaque(false);
        jPanel_buttons.setPreferredSize(new java.awt.Dimension(244, 519));

        btn_open_dataMaintenance_Druckrahmen.setText("1. Druckrahmen");
        btn_open_dataMaintenance_Druckrahmen.setPreferredSize(new java.awt.Dimension(120, 30));
        btn_open_dataMaintenance_Druckrahmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_open_dataMaintenance_DruckrahmenActionPerformed(evt);
            }
        });

        btn_open_dataMaintenance_Segmentrahmen.setText("2. Segmentrahmen");
        btn_open_dataMaintenance_Segmentrahmen.setPreferredSize(new java.awt.Dimension(120, 30));
        btn_open_dataMaintenance_Segmentrahmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_open_dataMaintenance_SegmentrahmenActionPerformed(evt);
            }
        });

        btn_open_dataMaintenance_Unterbauleiste.setText("3. Unterbauleiste");
        btn_open_dataMaintenance_Unterbauleiste.setPreferredSize(new java.awt.Dimension(120, 30));
        btn_open_dataMaintenance_Unterbauleiste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_open_dataMaintenance_UnterbauleisteActionPerformed(evt);
            }
        });

        btn_open_dataMaintenance_Kühlplatte.setText("4. Kühlplatte");
        btn_open_dataMaintenance_Kühlplatte.setPreferredSize(new java.awt.Dimension(120, 30));
        btn_open_dataMaintenance_Kühlplatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_open_dataMaintenance_KühlplatteActionPerformed(evt);
            }
        });

        btn_open_dataMaintenance_Grundplatte.setText("5. Grundplatte");
        btn_open_dataMaintenance_Grundplatte.setPreferredSize(new java.awt.Dimension(120, 30));
        btn_open_dataMaintenance_Grundplatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_open_dataMaintenance_GrundplatteActionPerformed(evt);
            }
        });

        btn_open_dataMaintenance_Druckplatte.setText("6. Druckplatte");
        btn_open_dataMaintenance_Druckplatte.setPreferredSize(new java.awt.Dimension(120, 30));
        btn_open_dataMaintenance_Druckplatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_open_dataMaintenance_DruckplatteActionPerformed(evt);
            }
        });

        btn_open_dataMaintenance_Grundformstamm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_open_dataMaintenance_Grundformstamm.setText("Grundformstamm");
        btn_open_dataMaintenance_Grundformstamm.setPreferredSize(new java.awt.Dimension(120, 30));
        btn_open_dataMaintenance_Grundformstamm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_open_dataMaintenance_GrundformstammActionPerformed(evt);
            }
        });

        btn_open_dataMaintenance_Werkzeugstamm.setText("Manager Werkzeugstamm");
        btn_open_dataMaintenance_Werkzeugstamm.setPreferredSize(new java.awt.Dimension(120, 30));
        btn_open_dataMaintenance_Werkzeugstamm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_open_dataMaintenance_WerkzeugstammActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_buttonsLayout = new javax.swing.GroupLayout(jPanel_buttons);
        jPanel_buttons.setLayout(jPanel_buttonsLayout);
        jPanel_buttonsLayout.setHorizontalGroup(
            jPanel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_buttonsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_open_dataMaintenance_Werkzeugstamm, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_buttonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_open_dataMaintenance_Kühlplatte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(btn_open_dataMaintenance_Unterbauleiste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_open_dataMaintenance_Grundplatte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_open_dataMaintenance_Druckplatte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_open_dataMaintenance_Druckrahmen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_open_dataMaintenance_Segmentrahmen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_open_dataMaintenance_Grundformstamm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_buttonsLayout.setVerticalGroup(
            jPanel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_buttonsLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(btn_open_dataMaintenance_Druckrahmen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_open_dataMaintenance_Segmentrahmen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_open_dataMaintenance_Unterbauleiste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_open_dataMaintenance_Kühlplatte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_open_dataMaintenance_Grundplatte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_open_dataMaintenance_Druckplatte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 325, Short.MAX_VALUE)
                .addComponent(btn_open_dataMaintenance_Grundformstamm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_open_dataMaintenance_Werkzeugstamm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout jPanel_mainLayout = new javax.swing.GroupLayout(jPanel_main);
        jPanel_main.setLayout(jPanel_mainLayout);
        jPanel_mainLayout.setHorizontalGroup(
            jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_buttons, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        jPanel_mainLayout.setVerticalGroup(
            jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_buttons, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
        );

        jPanel_footer.setOpaque(false);

        btn_exitProgram.setBackground(new java.awt.Color(255, 153, 153));
        btn_exitProgram.setText("Programm beenden");
        btn_exitProgram.setPreferredSize(new java.awt.Dimension(125, 30));
        btn_exitProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitProgramActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_footerLayout = new javax.swing.GroupLayout(jPanel_footer);
        jPanel_footer.setLayout(jPanel_footerLayout);
        jPanel_footerLayout.setHorizontalGroup(
            jPanel_footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_footerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_exitProgram, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_footerLayout.setVerticalGroup(
            jPanel_footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_footerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_exitProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_baseLayout = new javax.swing.GroupLayout(jPanel_base);
        jPanel_base.setLayout(jPanel_baseLayout);
        jPanel_baseLayout.setHorizontalGroup(
            jPanel_baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_footer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_baseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel_baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_baseLayout.setVerticalGroup(
            jPanel_baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_baseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 636, Short.MAX_VALUE)
                .addComponent(jPanel_footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel_baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_baseLayout.createSequentialGroup()
                    .addComponent(jPanel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(59, 59, 59)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_open_dataMaintenance_DruckrahmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_open_dataMaintenance_DruckrahmenActionPerformed
        // TODO add your handling code here:
        if (myDMDruckrahmen != null && myDMDruckrahmen.getInstance() >= 1) {
            myDMDruckrahmen.setAlwaysOnTop(true);
            myDMDruckrahmen.setAlwaysOnTop(false);
        }
        else {
            myDMDruckrahmen = new Frame_DataMaintenance_Druckrahmen();
            myDMDruckrahmen.setTitle("Stammdaten-Pflege: Druckrahmen");
            myDMDruckrahmen.setSize(1080, Toolkit.getDefaultToolkit().getScreenSize().height - 30);
            myDMDruckrahmen.setLocation(245, 0);
            myDMDruckrahmen.setVisible(true);
        }
    }//GEN-LAST:event_btn_open_dataMaintenance_DruckrahmenActionPerformed

    private void btn_open_dataMaintenance_SegmentrahmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_open_dataMaintenance_SegmentrahmenActionPerformed
        // TODO add your handling code here:
        if (myDMSegmentrahmen != null && myDMSegmentrahmen.getInstance() >= 1) {
            myDMSegmentrahmen.setAlwaysOnTop(true);
            myDMSegmentrahmen.setAlwaysOnTop(false);
        }
        else {
            myDMSegmentrahmen = new Frame_DataMaintenance_Segmentrahmen();
            myDMSegmentrahmen.setTitle("Stammdaten-Pflege: Segmentrahmen");
            myDMSegmentrahmen.setSize(1080, Toolkit.getDefaultToolkit().getScreenSize().height - 30);
            myDMSegmentrahmen.setLocation(245, 0);
            myDMSegmentrahmen.setVisible(true);
        }
    }//GEN-LAST:event_btn_open_dataMaintenance_SegmentrahmenActionPerformed

    private void btn_open_dataMaintenance_UnterbauleisteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_open_dataMaintenance_UnterbauleisteActionPerformed
        // TODO add your handling code here:
        if (myDMUnterbauleiste != null && myDMUnterbauleiste.getInstance() >= 1) {
            myDMUnterbauleiste.setAlwaysOnTop(true);
            myDMUnterbauleiste.setAlwaysOnTop(false);
        }
        else {
            myDMUnterbauleiste = new Frame_DataMaintenance_Unterbauleiste();
            myDMUnterbauleiste.setTitle("Stammdaten-Pflege: Unterbauleiste");
            myDMUnterbauleiste.setSize(925, Toolkit.getDefaultToolkit().getScreenSize().height - 30);
            myDMUnterbauleiste.setLocation(245, 0);
            myDMUnterbauleiste.setVisible(true);
        }
    }//GEN-LAST:event_btn_open_dataMaintenance_UnterbauleisteActionPerformed

    private void btn_open_dataMaintenance_KühlplatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_open_dataMaintenance_KühlplatteActionPerformed
        // TODO add your handling code here:
        if (myDMKühlplatte != null && myDMKühlplatte.getInstance() >= 1) {
            myDMKühlplatte.setAlwaysOnTop(true);
            myDMKühlplatte.setAlwaysOnTop(false);
        }
        else {
            myDMKühlplatte = new Frame_DataMaintenance_Kühlplatte();
            myDMKühlplatte.setTitle("Stammdaten-Pflege: Kühlplatte");
            myDMKühlplatte.setSize(1080, Toolkit.getDefaultToolkit().getScreenSize().height - 30);
            myDMKühlplatte.setLocation(245, 0);
            myDMKühlplatte.setVisible(true);
        }
    }//GEN-LAST:event_btn_open_dataMaintenance_KühlplatteActionPerformed

    private void btn_open_dataMaintenance_GrundplatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_open_dataMaintenance_GrundplatteActionPerformed
        // TODO add your handling code here:
        if (myDMGrundplatte != null && myDMGrundplatte.getInstance() >= 1) {
            myDMGrundplatte.setAlwaysOnTop(true);
            myDMGrundplatte.setAlwaysOnTop(false);
        }
        else {
            myDMGrundplatte = new Frame_DataMaintenance_Grundplatte();
            myDMGrundplatte.setTitle("Stammdaten-Pflege: Grundplatte");
            myDMGrundplatte.setSize(1080, Toolkit.getDefaultToolkit().getScreenSize().height - 30);
            myDMGrundplatte.setLocation(245, 0);
            myDMGrundplatte.setVisible(true);
        }
    }//GEN-LAST:event_btn_open_dataMaintenance_GrundplatteActionPerformed

    private void btn_open_dataMaintenance_DruckplatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_open_dataMaintenance_DruckplatteActionPerformed
        // TODO add your handling code here:
        if (myDMDruckplatte != null && myDMDruckplatte.getInstance() >= 1) {
            myDMDruckplatte.setAlwaysOnTop(true);
            myDMDruckplatte.setAlwaysOnTop(false);
        }
        else {
            myDMDruckplatte = new Frame_DataMaintenance_Druckplatte();
            myDMDruckplatte.setTitle("Stammdaten-Pflege: Druckplatte");
            myDMDruckplatte.setSize(1400, Toolkit.getDefaultToolkit().getScreenSize().height - 30);
            myDMDruckplatte.setLocation(245, 0);
            myDMDruckplatte.setVisible(true);
        }
    }//GEN-LAST:event_btn_open_dataMaintenance_DruckplatteActionPerformed

    private void btn_open_dataMaintenance_WerkzeugstammActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_open_dataMaintenance_WerkzeugstammActionPerformed
        // TODO add your handling code here:
        InstanceCount = 0;
        this.dispose();
    }//GEN-LAST:event_btn_open_dataMaintenance_WerkzeugstammActionPerformed

    private void btn_exitProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitProgramActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_exitProgramActionPerformed

    private void btn_open_dataMaintenance_GrundformstammActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_open_dataMaintenance_GrundformstammActionPerformed
        // TODO add your handling code here:
        if (myGrundformstamm != null && myGrundformstamm.getInstance() >= 1) {
            myGrundformstamm.setAlwaysOnTop(true);
            myGrundformstamm.setAlwaysOnTop(false);
        }
        else {
            myGrundformstamm = new Frame_DataMaintenance_Grundformstamm();
            myGrundformstamm.setTitle("Stammdaten-Pflege: Grundformstamm");
            myGrundformstamm.setSize(Toolkit.getDefaultToolkit().getScreenSize().width, Toolkit.getDefaultToolkit().getScreenSize().height - 30);
            //            myManagerGrundform.setLocation(245, 0);
            myGrundformstamm.setVisible(true);
        }
    }//GEN-LAST:event_btn_open_dataMaintenance_GrundformstammActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Grundform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Grundform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Grundform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Grundform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Frame_Grundform().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exitProgram;
    private javax.swing.JButton btn_open_dataMaintenance_Druckplatte;
    private javax.swing.JButton btn_open_dataMaintenance_Druckrahmen;
    private javax.swing.JButton btn_open_dataMaintenance_Grundformstamm;
    private javax.swing.JButton btn_open_dataMaintenance_Grundplatte;
    private javax.swing.JButton btn_open_dataMaintenance_Kühlplatte;
    private javax.swing.JButton btn_open_dataMaintenance_Segmentrahmen;
    private javax.swing.JButton btn_open_dataMaintenance_Unterbauleiste;
    private javax.swing.JButton btn_open_dataMaintenance_Werkzeugstamm;
    private javax.swing.JPanel jPanel_base;
    private javax.swing.JPanel jPanel_buttons;
    private javax.swing.JPanel jPanel_footer;
    private javax.swing.JPanel jPanel_main;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_infoAboutSequence;
    // End of variables declaration//GEN-END:variables
}
