/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DBTools.DB_ConnectionManager;
import java.awt.Point;
import java.awt.MouseInfo;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author schmidtu
 */
public class Frame_DataMaintenance_Werkzeugstamm extends javax.swing.JFrame {

    /**
     * Creates new form Frame_DataMaintenance_Werkzeugstamm
     */
    public Frame_DataMaintenance_Werkzeugstamm() {
        initComponents();
    }    
    
    boolean myAnswerIfConnected;           
    DB_ConnectionManager MY_DBCM; 
    Connection myConnection;
    DefaultTableModel myTableModel;
    String Old_Key;
    String Old_DescriptionValue;
    String Old_LengthValue;
    String Old_WidthValue;
    String Old_PropertyValue;
    int OldSelection; 
    String DataSet_Mode;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_table = new javax.swing.JPanel();
        jTextField_searchValue1 = new javax.swing.JTextField();
        btn_deleteSearchValue1 = new javax.swing.JButton();
        jScrollPane_dbData = new javax.swing.JScrollPane();
        jTable_dbData = new javax.swing.JTable();
        lbl_search1 = new javax.swing.JLabel();
        lbl_rowCount = new javax.swing.JLabel();
        btn_getCurrentDBData = new javax.swing.JButton();
        lbl_tableName = new javax.swing.JLabel();
        jPanel_buttonsForEdit = new javax.swing.JPanel();
        btn_new = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_accept = new javax.swing.JButton();
        lbl_key = new javax.swing.JLabel();
        lbl_valueDescription = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JButton();
        btn_duplicate = new javax.swing.JButton();
        jFormattedTextField_key = new javax.swing.JFormattedTextField();
        jFormattedTextField_valueDescription = new javax.swing.JFormattedTextField();
        jFormattedTextField_valueLength = new javax.swing.JFormattedTextField();
        lbl_valueLength = new javax.swing.JLabel();
        jFormattedTextField_valueWidth = new javax.swing.JFormattedTextField();
        lbl_valueWidth = new javax.swing.JLabel();
        jFormattedTextField_propertyValue = new javax.swing.JFormattedTextField();
        lbl_valueProperty = new javax.swing.JLabel();
        btn_openDialog_Materialtyp = new javax.swing.JButton();
        jFormattedTextField_propertyDescription = new javax.swing.JTextField();
        jPanel_footer = new javax.swing.JPanel();
        btn_close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_deleteSearchValue1.setText("X");
        btn_deleteSearchValue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteSearchValue1ActionPerformed(evt);
            }
        });

        jTable_dbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KP Artikel-Nr. (Key)", "GF - Grundform-ID", "KWV - Vorstempel", "KWS - Schnitt", "KSB - Stanzbrille", "B - Stanzblech-ID", "KWR - Stapelung", "KWN - Niederhalter", "STAL", "FK - Käfig", "ASB - Ausbrechstempel", "Schriftzug", "Materialtyp-ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_dbData.setRowHeight(20);
        jTable_dbData.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable_dbData.setShowVerticalLines(false);
        jTable_dbData.getTableHeader().setReorderingAllowed(false);
        jTable_dbData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable_dbDataMousePressed(evt);
            }
        });
        jTable_dbData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable_dbDataKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTable_dbDataKeyTyped(evt);
            }
        });
        jScrollPane_dbData.setViewportView(jTable_dbData);

        lbl_search1.setText("Suchen");

        lbl_rowCount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        btn_getCurrentDBData.setText("Aktualisieren");
        btn_getCurrentDBData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_getCurrentDBDataActionPerformed(evt);
            }
        });

        lbl_tableName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_tableName.setText("Tabelle: Werkzeugstamm");

        javax.swing.GroupLayout jPanel_tableLayout = new javax.swing.GroupLayout(jPanel_table);
        jPanel_table.setLayout(jPanel_tableLayout);
        jPanel_tableLayout.setHorizontalGroup(
            jPanel_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_tableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_dbData)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_tableLayout.createSequentialGroup()
                        .addGroup(jPanel_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_tableLayout.createSequentialGroup()
                                .addComponent(jTextField_searchValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_deleteSearchValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_search1)
                            .addComponent(lbl_tableName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_rowCount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_tableLayout.createSequentialGroup()
                                .addComponent(btn_getCurrentDBData)
                                .addGap(8, 8, 8)))))
                .addContainerGap())
        );
        jPanel_tableLayout.setVerticalGroup(
            jPanel_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_tableLayout.createSequentialGroup()
                .addGroup(jPanel_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_tableLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbl_tableName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_search1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_searchValue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_deleteSearchValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_tableLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btn_getCurrentDBData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_rowCount, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_dbData, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel_buttonsForEdit.setBorder(javax.swing.BorderFactory.createTitledBorder("Bearbeitung"));

        btn_new.setText("Neu");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        btn_edit.setText("Bearbeiten");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_delete.setText("Löschen");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_accept.setText("Übernehmen");
        btn_accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_acceptActionPerformed(evt);
            }
        });

        lbl_key.setText("Stanzblech-ID (Key)");

        lbl_valueDescription.setText("Stanzblech-Bezeichnung");

        btn_cancel.setText("Abbrechen");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_duplicate.setText("Duplizieren");
        btn_duplicate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_duplicateActionPerformed(evt);
            }
        });

        jFormattedTextField_key.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextField_key.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextField_key.setEnabled(false);

        jFormattedTextField_valueDescription.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextField_valueDescription.setEnabled(false);

        jFormattedTextField_valueLength.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFormattedTextField_valueLength.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextField_valueLength.setEnabled(false);

        lbl_valueLength.setText("Länge");

        jFormattedTextField_valueWidth.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFormattedTextField_valueWidth.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextField_valueWidth.setEnabled(false);

        lbl_valueWidth.setText("Breite");

        jFormattedTextField_propertyValue.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextField_propertyValue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextField_propertyValue.setEnabled(false);

        lbl_valueProperty.setText("Eigenschaft");

        btn_openDialog_Materialtyp.setText("X");
        btn_openDialog_Materialtyp.setEnabled(false);
        btn_openDialog_Materialtyp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_openDialog_MaterialtypActionPerformed(evt);
            }
        });

        jFormattedTextField_propertyDescription.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextField_propertyDescription.setEnabled(false);

        javax.swing.GroupLayout jPanel_buttonsForEditLayout = new javax.swing.GroupLayout(jPanel_buttonsForEdit);
        jPanel_buttonsForEdit.setLayout(jPanel_buttonsForEditLayout);
        jPanel_buttonsForEditLayout.setHorizontalGroup(
            jPanel_buttonsForEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_buttonsForEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_buttonsForEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_buttonsForEditLayout.createSequentialGroup()
                        .addGroup(jPanel_buttonsForEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_key, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField_key, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_buttonsForEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_buttonsForEditLayout.createSequentialGroup()
                                .addComponent(lbl_valueDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 421, Short.MAX_VALUE))
                            .addComponent(jFormattedTextField_valueDescription))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_buttonsForEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextField_valueLength, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_valueLength, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_buttonsForEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextField_valueWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_valueWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_buttonsForEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel_buttonsForEditLayout.createSequentialGroup()
                                .addComponent(lbl_valueProperty, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_openDialog_Materialtyp, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_buttonsForEditLayout.createSequentialGroup()
                                .addComponent(jFormattedTextField_propertyValue, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextField_propertyDescription)))
                        .addContainerGap())
                    .addGroup(jPanel_buttonsForEditLayout.createSequentialGroup()
                        .addGroup(jPanel_buttonsForEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_buttonsForEditLayout.createSequentialGroup()
                                .addComponent(btn_accept)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_cancel))
                            .addGroup(jPanel_buttonsForEditLayout.createSequentialGroup()
                                .addComponent(btn_new)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_edit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_duplicate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_delete)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel_buttonsForEditLayout.setVerticalGroup(
            jPanel_buttonsForEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_buttonsForEditLayout.createSequentialGroup()
                .addGroup(jPanel_buttonsForEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_buttonsForEditLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lbl_valueWidth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField_valueWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_buttonsForEditLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel_buttonsForEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_buttonsForEditLayout.createSequentialGroup()
                                .addGroup(jPanel_buttonsForEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_buttonsForEditLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_valueProperty))
                                    .addComponent(btn_openDialog_Materialtyp, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_buttonsForEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFormattedTextField_propertyValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField_propertyDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_buttonsForEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel_buttonsForEditLayout.createSequentialGroup()
                                    .addComponent(lbl_valueDescription)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jFormattedTextField_valueDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel_buttonsForEditLayout.createSequentialGroup()
                                    .addGroup(jPanel_buttonsForEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_key)
                                        .addComponent(lbl_valueLength))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel_buttonsForEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jFormattedTextField_key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jFormattedTextField_valueLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGroup(jPanel_buttonsForEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_new)
                    .addComponent(btn_edit)
                    .addComponent(btn_delete)
                    .addComponent(btn_duplicate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_buttonsForEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_accept)
                    .addComponent(btn_cancel))
                .addContainerGap())
        );

        btn_close.setText("Schließen");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_footerLayout = new javax.swing.GroupLayout(jPanel_footer);
        jPanel_footer.setLayout(jPanel_footerLayout);
        jPanel_footerLayout.setHorizontalGroup(
            jPanel_footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_footerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_close)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_footerLayout.setVerticalGroup(
            jPanel_footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_footerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_close)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_buttonsForEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_buttonsForEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getDBConnection() { 
        MY_DBCM = new DB_ConnectionManager("jdbc:sqlserver://HV-ABAS-SQL;databaseName=DiafBDE;integratedSecurity=true", "CONNECT");
        if (!MY_DBCM.isConnnected()) {
            JOptionPane.showMessageDialog(null,
                    "Der Verbindungs-Aufbau zur Datenbank ist gescheitert. Bitte wenden Sie sich an den Entwickler.",
                    "Fehler",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }        
    }
   
    private void get_DBTableData() {   
        
        try
        { 
            MY_DBCM.setConnection_CLOSED("jdbc:sqlserver://HV-ABAS-SQL;databaseName=DiafBDE;integratedSecurity=true", "DISCONNECT");
            MY_DBCM = new DB_ConnectionManager("jdbc:sqlserver://HV-ABAS-SQL;databaseName=DiafBDE;integratedSecurity=true", "CONNECT");
            myConnection = MY_DBCM.getConnection();
            Statement myStatement = myConnection.createStatement();
//            String myTempSQL = "CREATE TABLE #tempSegment FROM DiafBDE.dbo.T_Segment";
            String mySQL = "SELECT * FROM DiafBDE.dbo.T_Stanzblechstamm"; // ORDER BY T_Segment.pKey_KP"; // WHERE tma_abt='Technik'";
            ResultSet myResultSet = myStatement.executeQuery(mySQL);            
            int myColumns = myResultSet.getMetaData().getColumnCount();
            myTableModel = (DefaultTableModel) jTable_dbData.getModel();
            int allOldRows = myTableModel.getRowCount();
            if (allOldRows > 0) {
                myTableModel.setRowCount(0);
            }
            while (myResultSet.next()) {
                  
                String[] myValue = new String[myColumns];
                
                for (int i = 1; i <= myColumns; i++) {
                          
                    String myDataSet = myResultSet.getString(i);
                    myValue[i-1] = myDataSet;
                }  
                myTableModel.addRow(myValue); 
            }
            if (!myResultSet.next()) {
                
                return;
            } 
        }
        catch (SQLException myException )
        {
            System.out.println(myException);
        }
        finally {
            try {
                if (myConnection != null && !myConnection.isClosed()) {
                    myConnection.close();
                }
            } catch (SQLException myException) {
                System.out.println(myException);
            }
        } 
    }
    
    private void btn_deleteSearchValue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteSearchValue1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_deleteSearchValue1ActionPerformed

    private void jTable_dbDataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_dbDataMousePressed
        // TODO add your handling code here:
        if (myTableModel.getRowCount() > 0) {
            OldSelection = jTable_dbData.getSelectedRow();
            set_valuesIntoTextFields();
        }
    }//GEN-LAST:event_jTable_dbDataMousePressed

    private void jTable_dbDataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable_dbDataKeyPressed
        // TODO add your handling code here:
        if (myTableModel.getRowCount() > 0) {
            OldSelection = jTable_dbData.getSelectedRow();
            set_valuesIntoTextFields();
        }
    }//GEN-LAST:event_jTable_dbDataKeyPressed

    private void jTable_dbDataKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable_dbDataKeyTyped
        // TODO add your handling code here:
        //        if (myTableModel.getRowCount() > 0) {
            //            OldSelection = jTable_dbData.getSelectedRow();
            //            set_valuesIntoTextFields();
            //        }
    }//GEN-LAST:event_jTable_dbDataKeyTyped
    
    private void set_textFieldsEmpty() {
        jFormattedTextField_key.setText("");
        jFormattedTextField_valueDescription.setText("");
        jFormattedTextField_valueLength.setText("");
        jFormattedTextField_valueWidth.setText("");
        jFormattedTextField_propertyValue.setText(""); 
        jFormattedTextField_propertyDescription.setText("");        
    }
    
    private void set_oldValues() {        
        Old_Key = jFormattedTextField_key.getText().trim();
        Old_DescriptionValue = jFormattedTextField_valueDescription.getText().trim();
        Old_LengthValue = jFormattedTextField_valueLength.getText().trim();
        Old_WidthValue = jFormattedTextField_valueWidth.getText().trim();
        Old_PropertyValue = jFormattedTextField_propertyValue.getText().trim();
    }
    
    private void get_oldValues() {         
        jFormattedTextField_key.setText(Old_Key);
        jFormattedTextField_valueDescription.setText(Old_DescriptionValue); 
        jFormattedTextField_valueLength.setText(Old_LengthValue); 
        jFormattedTextField_valueWidth.setText(Old_WidthValue); 
        jFormattedTextField_propertyValue.setText(Old_PropertyValue);   
    }
    
    private void set_textFieldsEnabled(boolean aBoolean) {
        
        jFormattedTextField_key.setEnabled(aBoolean);
        jFormattedTextField_valueDescription.setEnabled(true); 
        jFormattedTextField_valueLength.setEnabled(true); 
        jFormattedTextField_valueWidth.setEnabled(true); 
        jFormattedTextField_propertyValue.setEnabled(true); 
        jFormattedTextField_propertyDescription.setEnabled(true);
    }
    
    private void set_textFieldsDisabled() {
        
        jFormattedTextField_key.setEnabled(false);
        jFormattedTextField_valueDescription.setEnabled(false);
        jFormattedTextField_valueLength.setEnabled(false); 
        jFormattedTextField_valueWidth.setEnabled(false); 
        jFormattedTextField_propertyValue.setEnabled(false);    
        jFormattedTextField_propertyDescription.setEnabled(false);        
    }
    private void btn_getCurrentDBDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_getCurrentDBDataActionPerformed
        // TODO add your handling code here:
        get_DBTableData();
        btn_new.setEnabled(true);
        btn_edit.setEnabled(false);
        btn_duplicate.setEnabled(false);
        btn_delete.setEnabled(false);
        btn_accept.setEnabled(false);
        btn_cancel.setEnabled(false);
        set_textFieldsEmpty();
    }//GEN-LAST:event_btn_getCurrentDBDataActionPerformed

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        // TODO add your handling code here:
        DataSet_Mode = "new";
        set_textFieldsEnabled(true);
        set_oldValues();
        set_textFieldsEmpty();
        jFormattedTextField_key.requestFocus();
        btn_new.setEnabled(false);
        btn_edit.setEnabled(false);
        btn_duplicate.setEnabled(false);
        btn_delete.setEnabled(false);
        btn_accept.setEnabled(true);
        btn_cancel.setEnabled(true);
        btn_openDialog_Materialtyp.setEnabled(true);
    }//GEN-LAST:event_btn_newActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        DataSet_Mode = "edit";
        set_oldValues();
        set_textFieldsEnabled(false);
        jFormattedTextField_valueDescription.requestFocus();
        btn_new.setEnabled(false);
        btn_edit.setEnabled(false);
        btn_duplicate.setEnabled(false);
        btn_delete.setEnabled(false);
        btn_accept.setEnabled(true);
        btn_cancel.setEnabled(true);
        btn_openDialog_Materialtyp.setEnabled(true);
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        DataSet_Mode = "delete";
        if (DataSet_Mode.equals("delete") && test_isDataSetInDB(jFormattedTextField_key.getText().trim()) == true) {
            int myAnswer = JOptionPane.showConfirmDialog(null,
                "Soll der Datensatz Stanzblech-ID (Key): \n\n >> " + jFormattedTextField_key.getText().trim() + " << \n\n wirklich gelöscht werden?",
                "Datensatz löschen?",
                JOptionPane.YES_NO_OPTION);
            if (myAnswer == 1) {
                return;
            }
            else {
                do_deleteDataSet_inDB();
                get_DBTableData();
                set_textFieldsEmpty();
                set_textFieldsDisabled();
                btn_new.setEnabled(true);
                btn_edit.setEnabled(false);
                btn_duplicate.setEnabled(false);
                btn_delete.setEnabled(false);
                btn_accept.setEnabled(false);
                btn_cancel.setEnabled(false);
                lbl_rowCount.setText(String.valueOf(myTableModel.getRowCount()));
            }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed
    
    private boolean test_isDataSetInDB(String aString) {
        boolean myAnswer = false;
        for (int myRow = 0; myRow < jTable_dbData.getRowCount(); ++myRow ) {
            if (myTableModel.getValueAt(myRow, 0).toString().trim().equals(aString))
                myAnswer = true;           
        }
        return myAnswer;
    }
    
    private void do_deleteDataSet_inDB() {        
        try
        {
            MY_DBCM.setConnection_CLOSED("jdbc:sqlserver://HV-ABAS-SQL;databaseName=DiafBDE;integratedSecurity=true", "DISCONNECT");
            MY_DBCM = new DB_ConnectionManager("jdbc:sqlserver://HV-ABAS-SQL;databaseName=DiafBDE;integratedSecurity=true", "CONNECT");
            if (MY_DBCM.isConnnected()) 
            { 
            myConnection = MY_DBCM.getConnection();
            Statement myStatement = myConnection.createStatement();
            myStatement.executeUpdate("DELETE FROM DiafBDE.dbo.T_Stanzblechstamm WHERE pKey_Stanzblech_ID = '" + jFormattedTextField_key.getText() + "'");             
            }   
        }
        catch (/*ClassNotFoundException |*/ SQLException myException )
        {
        }
        finally {
            try {
                if (myConnection != null && !myConnection.isClosed()) {
                    myConnection.close();
                }
            } catch (SQLException myException) {
            }
        }         
    }
    
    private void do_updateDataSet_inDB() {        
        try
        {
            MY_DBCM.setConnection_CLOSED("jdbc:sqlserver://HV-ABAS-SQL;databaseName=DiafBDE;integratedSecurity=true", "DISCONNECT");
            MY_DBCM = new DB_ConnectionManager("jdbc:sqlserver://HV-ABAS-SQL;databaseName=DiafBDE;integratedSecurity=true", "CONNECT");
            if (MY_DBCM.isConnnected()) 
            { 
            myConnection = MY_DBCM.getConnection();
            System.out.println("UPDATE DiafBDE.dbo.T_Stanzblechstamm SET Bezeichnung = '" + jFormattedTextField_valueDescription.getText().trim() + 
                    "', Länge = '" + jFormattedTextField_valueLength.getText().trim() + 
                    "', Breite = '" + jFormattedTextField_valueWidth.getText().trim() +
                    "', Eigenschaft = '" + jFormattedTextField_propertyValue.getText().trim() +
                    "' WHERE pKey_Stanzblech_ID = '" + jFormattedTextField_key.getText().trim() + "'");
            Statement myStatement = myConnection.createStatement();
            myStatement.executeUpdate("UPDATE DiafBDE.dbo.T_Stanzblechstamm SET Bezeichnung = '" + jFormattedTextField_valueDescription.getText().trim() + 
                    "', Länge = '" + ((Number) jFormattedTextField_valueLength.getValue()).doubleValue() + 
                    "', Breite = '" + ((Number) jFormattedTextField_valueWidth.getValue()).doubleValue() +
                    "', Eigenschaft = '" + ((Number) jFormattedTextField_propertyValue.getValue()).intValue() +
                    "' WHERE pKey_Stanzblech_ID = '" + jFormattedTextField_key.getText() + "'");             
            } 
        }
        catch (/*ClassNotFoundException |*/ SQLException myException )
        {
        }
        finally {
            try {
                if (myConnection != null && !myConnection.isClosed()) {
                    myConnection.close();
                }
            } catch (SQLException myException) {
            }
        }         
    }
    
    private void btn_acceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_acceptActionPerformed
        // TODO add your handling code here:
        if (jFormattedTextField_key.getText().isEmpty() || jFormattedTextField_valueDescription.getText().isEmpty()
            || jFormattedTextField_valueLength.getText().isEmpty() || jFormattedTextField_valueWidth.getText().isEmpty()
            || jFormattedTextField_propertyValue.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null,
                "Der Datensatz ist teilweise leer. Erfassen Sie Daten oder klicken Sie auf Abbrechen.",
                "Fehler",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        else {
            boolean myAnswer = test_isDataSetInDB(jFormattedTextField_key.getText().trim());

            if (myAnswer == true) {
                if (DataSet_Mode.equals("new")) {
                    JOptionPane.showMessageDialog(null,
                        "Es existiert schon ein Datensatz mit diesem Key: \n\n >> " + jFormattedTextField_key.getText().trim() + " <<.",
                        "Fehler",
                        JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if (DataSet_Mode.equals("edit")  && !Old_DescriptionValue.equals(jFormattedTextField_valueDescription.getText().trim())
                    || !Old_LengthValue.equals(jFormattedTextField_valueLength.getText().trim())
                    || !Old_WidthValue.equals(jFormattedTextField_valueWidth.getText().trim())
                    || !Old_PropertyValue.equals(jFormattedTextField_propertyValue.getText().trim())) {
                    do_updateDataSet_inDB();
                }
                if (DataSet_Mode.equals("duplicate")) {
                    JOptionPane.showMessageDialog(null,"Beim Duplizieren muss ein neuer Key vergeben werden.",
                        "Fehler",
                        JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            if (myAnswer == false) {
                if (DataSet_Mode.equals("new") || DataSet_Mode.equals("duplicate")) {
                    do_insertDataSet_intoDB();
                }
            }
            set_textFieldsDisabled();
            btn_new.setEnabled(true);
            btn_accept.setEnabled(false);
            btn_cancel.setEnabled(false);
            btn_openDialog_Materialtyp.setEnabled(false);
            if (jTable_dbData.getSelectedRow() > -1) {

                btn_edit.setEnabled(true);
                btn_duplicate.setEnabled(true);
                btn_delete.setEnabled(true);
            }
            else {
                btn_edit.setEnabled(false);
                btn_duplicate.setEnabled(false);
                btn_delete.setEnabled(false);
            }
            get_DBTableData();
            lbl_rowCount.setText(String.valueOf(myTableModel.getRowCount()));
        }
    }//GEN-LAST:event_btn_acceptActionPerformed

    private void do_insertDataSet_intoDB() {        
        try
        {
            MY_DBCM.setConnection_CLOSED("jdbc:sqlserver://HV-ABAS-SQL;databaseName=DiafBDE;integratedSecurity=true", "DISCONNECT");
            MY_DBCM = new DB_ConnectionManager("jdbc:sqlserver://HV-ABAS-SQL;databaseName=DiafBDE;integratedSecurity=true", "CONNECT");
            if (MY_DBCM.isConnnected()) 
            {   
            myConnection = MY_DBCM.getConnection();
            Statement myStatement = myConnection.createStatement();
            myStatement.executeUpdate("INSERT INTO DiafBDE.dbo.T_Stanzblechstamm (pKey_Stanzblech_ID, Bezeichnung, Länge, Breite, Eigenschaft)" 
                    + "VALUES ('" + ((Number)jFormattedTextField_key.getValue()).intValue() + "', '" 
                    + jFormattedTextField_valueDescription.getText().trim() + "', '" 
                    + ((Number) jFormattedTextField_valueLength.getValue()).floatValue() + "', '" 
                    + ((Number) jFormattedTextField_valueWidth.getValue()).floatValue() + "', '" 
                    + ((Number) jFormattedTextField_propertyValue.getValue()).intValue() +"')");             
            } 
        }
        catch (/*ClassNotFoundException |*/ SQLException myException )
        {
        }
        finally {
            try {
                if (myConnection != null && !myConnection.isClosed()) {
                    myConnection.close();
                }
            } catch (SQLException myException) {
            }
        }         
    }
    
    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        get_oldValues();
        set_textFieldsDisabled();
        btn_new.setEnabled(true);
        if (!Old_Key.equals("")) {
            btn_edit.setEnabled(true);
            btn_duplicate.setEnabled(true);
            btn_delete.setEnabled(true);
        }
        btn_accept.setEnabled(false);
        btn_cancel.setEnabled(false);
        btn_openDialog_Materialtyp.setEnabled(false);
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_duplicateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_duplicateActionPerformed
        // TODO add your handling code here:
        DataSet_Mode = "duplicate";
        set_oldValues();
        set_textFieldsEnabled(true);
        jFormattedTextField_key.requestFocus();
        btn_new.setEnabled(false);
        btn_edit.setEnabled(false);
        btn_duplicate.setEnabled(false);
        btn_delete.setEnabled(false);
        btn_accept.setEnabled(true);
        btn_cancel.setEnabled(true);
    }//GEN-LAST:event_btn_duplicateActionPerformed

    private void btn_openDialog_MaterialtypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_openDialog_MaterialtypActionPerformed
        // TODO add your handling code here:
        Dialog_DataUse_Materialtyp myDialog = new Dialog_DataUse_Materialtyp(this,true);
        myDialog.setTitle("Materialtyp");
        Point location = MouseInfo.getPointerInfo().getLocation();
        myDialog.setLocation(location.x + 20 , location.y - 40);
        myDialog.setVisible(true);
        int resultFromDialog_ID = myDialog.getChoosenMaterialtypID();
        String resultFromDialo_Descriptiong = myDialog.getChoosenMaterialtypDescription().trim();
        this.jFormattedTextField_propertyValue.setValue(resultFromDialog_ID);
        this.jFormattedTextField_propertyDescription.setText(resultFromDialo_Descriptiong);
    }//GEN-LAST:event_btn_openDialog_MaterialtypActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:
        if (MY_DBCM.isConnnected()) {
            MY_DBCM.setConnection_CLOSED("jdbc:sqlserver://HV-ABAS-SQL;databaseName=DiafBDE;integratedSecurity=true", "DISCONNECT");
        }
        this.dispose();
        //        }
    }//GEN-LAST:event_btn_closeActionPerformed

    
    private void set_valuesIntoTextFields() {
        
//        OldSelection = jTable_dbData.getSelectedRow();
        if(OldSelection != -1) {
            jFormattedTextField_key.setText(myTableModel.getValueAt(OldSelection, 0).toString());
            jFormattedTextField_valueDescription.setText(myTableModel.getValueAt(OldSelection, 1).toString());
            jFormattedTextField_valueLength.setText(myTableModel.getValueAt(OldSelection, 2).toString());
            jFormattedTextField_valueWidth.setText(myTableModel.getValueAt(OldSelection, 3).toString());
            jFormattedTextField_propertyValue.setText(myTableModel.getValueAt(OldSelection, 4).toString());
            if (myTableModel.getValueAt(OldSelection, 4).toString().equals("1")) {
                jFormattedTextField_propertyDescription.setText("hart");
            }
            else {
                jFormattedTextField_propertyDescription.setText("weich");
            }
            
            btn_edit.setEnabled(true);
            btn_duplicate.setEnabled(true);
            btn_delete.setEnabled(true); 
        }        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_DataMaintenance_Werkzeugstamm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_DataMaintenance_Werkzeugstamm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_DataMaintenance_Werkzeugstamm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_DataMaintenance_Werkzeugstamm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Frame_DataMaintenance_Werkzeugstamm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_accept;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_deleteSearchValue1;
    private javax.swing.JButton btn_duplicate;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_getCurrentDBData;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_openDialog_Materialtyp;
    private javax.swing.JFormattedTextField jFormattedTextField_key;
    private javax.swing.JTextField jFormattedTextField_propertyDescription;
    private javax.swing.JFormattedTextField jFormattedTextField_propertyValue;
    private javax.swing.JFormattedTextField jFormattedTextField_valueDescription;
    private javax.swing.JFormattedTextField jFormattedTextField_valueLength;
    private javax.swing.JFormattedTextField jFormattedTextField_valueWidth;
    private javax.swing.JPanel jPanel_buttonsForEdit;
    private javax.swing.JPanel jPanel_footer;
    private javax.swing.JPanel jPanel_table;
    private javax.swing.JScrollPane jScrollPane_dbData;
    private javax.swing.JTable jTable_dbData;
    private javax.swing.JTextField jTextField_searchValue1;
    private javax.swing.JLabel lbl_key;
    private javax.swing.JLabel lbl_rowCount;
    private javax.swing.JLabel lbl_search1;
    private javax.swing.JLabel lbl_tableName;
    private javax.swing.JLabel lbl_valueDescription;
    private javax.swing.JLabel lbl_valueLength;
    private javax.swing.JLabel lbl_valueProperty;
    private javax.swing.JLabel lbl_valueWidth;
    // End of variables declaration//GEN-END:variables
}
